import type { QuizQuestion } from "../types/database";
import { topicOf } from "./quizTopics";

// ═══════════════════════════════════════════════════════════════════════════
// HENGÂME QUIZ QUESTIONS POOL (TR / DE / EN)
// Categorized by locale, with difficulties (1=Easy, 2=Medium, 3=Hard/Chaos)
// Includes categories and fun facts for TV reveal cards.
// ═══════════════════════════════════════════════════════════════════════════

export const trQuestions: QuizQuestion[] = [
  // ─── GECE HAYATI & KAFE KÜLTÜRÜ ───
  {
    id: "tr_night_1",
    category: "🍸 GECE & KAFE",
    text: "Geleneksel bir 'Virgin Mojito'ya karakterini veren bitki hangisidir?",
    options: { A: "Fesleğen", B: "Nane", C: "Kekik", D: "Biberiye" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Nane yapraklarını ezmek değil, hafifçe bastırmak gerekir; ezilince acı tat veriyor.",
  },
  {
    id: "tr_night_2",
    category: "🍸 GECE & KAFE",
    text: "Kahve çekirdeği aslında botanik olarak nedir?",
    options: { A: "Ağaç Kabuğu", B: "Bir Meyvenin Çekirdeği", C: "Kök Yumrusu", D: "Yaprak Tomurcuğu" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Kahve çekirdekleri, 'kahve kirazı' adı verilen kırmızı meyvelerin içindeki tohumlardır.",
  },
  {
    id: "tr_night_3",
    category: "🍸 GECE & KAFE",
    text: "Bir espressonun üzerindeki altın rengi köpüğe ne ad verilir?",
    options: { A: "Krema", B: "Crema", C: "Köpük", D: "Foam" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Crema, taze çekirdekteki karbondioksitin basınç altında yağlarla birleşmesiyle oluşuyor; eskimiş kahvede neredeyse hiç çıkmıyor.",
  },

  // ─── MÜZİK & POPÜLER KÜLTÜR ───
  {
    id: "tr_music_1",
    category: "🎵 MÜZİK",
    text: "Spotify'da tüm zamanların ilk 3 milyar dinlenmeyi aşan şarkısı hangisidir?",
    options: { A: "Blinding Lights (The Weeknd)", B: "Shape of You (Ed Sheeran)", C: "Despacito (Luis Fonsi)", D: "Dance Monkey (Tones and I)" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ed Sheeran'ın 'Shape of You' şarkısı 2021'de 3 milyar barajını ilk geçen şarkı olmuştur.",
  },
  {
    id: "tr_music_2",
    category: "🎵 MÜZİK",
    text: "Efsanevi rock grubu Queen'in 'Bohemian Rhapsody' şarkısı hangi yılda yayınlanmıştır?",
    options: { A: "1969", B: "1975", C: "1982", D: "1989" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Plak şirketi şarkının 6 dakikalık süresini radyolar için çok uzun bulup ilk başta reddetmişti!",
  },
  {
    id: "tr_music_3",
    category: "🎵 MÜZİK",
    text: "Daft Punk'ın ikonik robot kaskları ilk olarak hangi albüm döneminde sahneye çıktı?",
    options: { A: "Homework", B: "Discovery", C: "Human After All", D: "Random Access Memories" },
    correctOption: "B",
    difficulty: 3,
    funFact: "İkili, 1999 yılında bir stüdyo patlamasında robota dönüştüklerini iddia eden eğlenceli bir hikaye uydurmuştu.",
  },

  // ─── SİNEMA & DİZİ ───
  {
    id: "tr_cinema_1",
    category: "🎬 SİNEMA",
    text: "'Matrix' filminde Neo'nun gerçeği görmek için seçtiği hap hangi renktir?",
    options: { A: "Mavi", B: "Kırmızı", C: "Yeşil", D: "Sarı" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Mavi hap illüzyon dolu Matrix'te uyumayı, Kırmızı hap ise acımasız gerçek dünyayı temsil eder.",
  },
  {
    id: "tr_cinema_2",
    category: "🎬 SİNEMA",
    text: "Quentin Tarantino'nun 'Pulp Fiction' filmindeki meşhur parlayan çantanın içinde ne olduğu filmde açıklanır mı?",
    options: { A: "Elmaslar", B: "Marcellus'un Ruhu", C: "Altın Külçeleri", D: "Hiçbir zaman açıklanmaz" },
    correctOption: "D",
    difficulty: 2,
    funFact: "Tarantino, çantanın içinde ne olduğunu izleyicinin hayal gücüne bırakmak için bilerek gizli tutmuştur.",
  },
  {
    id: "tr_cinema_3",
    category: "🎬 SİNEMA",
    text: "Yüzüklerin Efendisi serisinde 'Tek Yüzük' hangi dağın ateşinde dövülmüştür?",
    options: { A: "Hüküm Dağı (Mount Doom)", B: "Erebor Dağı", C: "Sisli Dağlar", D: "Caradhras" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Yüzük yalnızca dövüldüğü yer olan Hüküm Dağı'nın lavlarında yok edilebilir.",
  },

  // ─── ZEKA & MANTIK TUZAKLARI ───
  {
    id: "tr_brain_1",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bir yarışta ikinci sıradaki koşucuyu geçerseniz kaçıncı olursunuz?",
    options: { A: "Birinci", B: "İkinci", C: "Üçüncü", D: "Yarışı kazanırsınız" },
    correctOption: "B",
    difficulty: 1,
    funFact: "İkincinin yerini aldığınız için siz ikinci olursunuz, birinci hâlâ önünüzdedir!",
  },
  {
    id: "tr_brain_2",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bazı aylar 30, bazıları 31 çeker. Kaç ayda 28 gün vardır?",
    options: { A: "1 (Şubat)", B: "6", C: "12 (Hepsinde)", D: "Hiçbiri" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Yılın 12 ayının tamamında en az 28 gün bulunmaktadır!",
  },
  {
    id: "tr_brain_3",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bir tuğlanın ağırlığı 1 kg artı yarım tuğla kadardır. Bir tuğla kaç kg'dır?",
    options: { A: "1.5 kg", B: "2 kg", C: "2.5 kg", D: "3 kg" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Matematiksel olarak: X = 1 + X/2 denkleminden X = 2 kg çıkar.",
  },

  // ─── GENEL KÜLTÜR & COĞRAFYA ───
  {
    id: "tr_gen_1",
    category: "🌍 GENEL KÜLTÜR",
    text: "Dünyanın yüzölçümü bakımından en büyük okyanusu hangisidir?",
    options: { A: "Atlantik (Atlas)", B: "Pasifik (Büyük Okyanus)", C: "Hint Okyanusu", D: "Arktik Okyanusu" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Pasifik Okyanusu, dünyadaki tüm kara parçalarının toplamından daha geniş bir alanı kaplar!",
  },
  {
    id: "tr_gen_2",
    category: "🌍 GENEL KÜLTÜR",
    text: "Hangi element periyodik tabloda 'Au' simgesi ile gösterilir?",
    options: { A: "Gümüş", B: "Altın", C: "Alüminyum", D: "Bakır" },
    correctOption: "B",
    difficulty: 1,
    funFact: "'Au' simgesi, Latince 'parlayan şafak' anlamına gelen 'Aurum' kelimesinden gelir.",
  },
  {
    id: "tr_gen_3",
    category: "🌍 GENEL KÜLTÜR",
    text: "Mona Lisa tablosu günümüzde hangi müzede sergilenmektedir?",
    options: { A: "British Museum", B: "Prado Müzesi", C: "Louvre Müzesi", D: "Uffizi Galerisi" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Mona Lisa tablosunun kendi posta kutusu vardır ve her yıl binlerce aşk mektubu alır!",
  },
  {
    id: "tr_gen_4",
    category: "🌍 GENEL KÜLTÜR",
    text: "Nobel Edebiyat Ödülü'nü kazanan ilk Türk yazar kimdir?",
    options: { A: "Yaşar Kemal", B: "Orhan Pamuk", C: "Sabahattin Ali", D: "Nazım Hikmet" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Orhan Pamuk, Nobel Edebiyat Ödülü'nü 2006 yılında kazanmıştır.",
  },
  {
    id: "tr_gen_5",
    category: "🌍 GENEL KÜLTÜR",
    text: "Japonya'nın resmi para birimi nedir?",
    options: { A: "Yen", B: "Yuan", C: "Won", D: "Baht" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Japonca 'Yen', kelime anlamı olarak 'yuvarlak nesne' veya 'daire' demektir.",
  },

  // ─── BİLİM & TEKNOLOJİ ───
  {
    id: "tr_sci_1",
    category: "🚀 BİLİM & TEKNO",
    text: "Güneş Sistemi'ndeki en sıcak gezegen hangisidir?",
    options: { A: "Merkür", B: "Venüs", C: "Mars", D: "Jüpiter" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Güneş'e en yakın gezegen Merkür olsa da, yoğun sera gazı atmosferi nedeniyle en sıcağı Venüs'tür (465°C)!",
  },
  {
    id: "tr_sci_2",
    category: "🚀 BİLİM & TEKNO",
    text: "Tarihteki ilk bilgisayar programcısı olarak kabul edilen bilim insanı kimdir?",
    options: { A: "Alan Turing", B: "Ada Lovelace", C: "Nikola Tesla", D: "Charles Babbage" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Ada Lovelace, 1843 yılında mekanik bilgisayar için ilk algoritmayı yazmıştır.",
  },
  {
    id: "tr_sci_3",
    category: "🚀 BİLİM & TEKNO",
    text: "Işığın boşluktaki hızı saniyede yaklaşık kaç kilometredir?",
    options: { A: "150.000 km/s", B: "300.000 km/s", C: "500.000 km/s", D: "1.000.000 km/s" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Işık hızında seyahat edebilseydiniz, 1 saniyede Dünya'nın etrafını 7.5 kez turlayabilirdiniz!",
  },
  {
    id: "tr_sci_4",
    category: "🚀 BİLİM & TEKNO",
    text: "İnsan vücudundaki en güçlü ve en büyük kemik hangisidir?",
    options: { A: "Uyluk Kemiği (Femur)", B: "Kaval Kemiği", C: "Omurga", D: "Kafatası" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Femur kemiği betondan daha yüksek basınca ve vücut ağırlığının 30 katına kadar yüke dayanabilir.",
  },
  {
    id: "tr_sci_5",
    category: "🚀 BİLİM & TEKNO",
    text: "Ahtapotların kaç adet kalbi vardır?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Ahtapotların 3 kalbi ve mavi renkte kanı vardır!",
  },
  {
    id: "tr_cafe_10",
    category: "☕ KAHVE & KAFE",
    text: "Kahve bitkisinin anavatanı neresidir?",
    options: { A: "Brezilya", B: "Etiyopya", C: "Kolombiya", D: "Yemen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Efsaneye göre keçi çobanı Kaldi, keçilerinin kahve kirazı yedikten sonraki hâlini fark edip durumu keşfetmiş.",
  },
  {
    id: "tr_cafe_11",
    category: "☕ KAHVE & KAFE",
    text: "'Cappuccino' kelimesi kelime anlamıyla ne demek?",
    options: { A: "Küçük kukuleta", B: "Süt köpüğü", C: "Çift kahve", D: "Sabah içeceği" },
    correctOption: "A",
    difficulty: 2,
    funFact: "İsim, Kapuçin rahiplerinin cüppe renginden geliyor.",
  },
  {
    id: "tr_cafe_12",
    category: "☕ KAHVE & KAFE",
    text: "Türk kahvesi geleneksel olarak neyle pişirilir?",
    options: { A: "Filtre makinesi", B: "Cezve", C: "French press", D: "Su ısıtıcısı" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Telve fincanda kalır ve geleneksel olarak fal bakmakta kullanılır.",
  },
  {
    id: "tr_cafe_13",
    category: "☕ KAHVE & KAFE",
    text: "Matcha neyden yapılır?",
    options: { A: "Kavrulmuş pirinç", B: "Toz hâline getirilmiş yeşil çay yaprağı", C: "Kurutulmuş nane", D: "Fermente kakao" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Matcha'da yaprağın tamamı içildiği için kafein oranı demlenmiş yeşil çaydan yüksek.",
  },
  {
    id: "tr_cafe_14",
    category: "☕ KAHVE & KAFE",
    text: "'Cold brew' nedir?",
    options: { A: "Sıcak demlenip soğutulan kahve", B: "Soğuk suyla uzun sürede demlenen kahve", C: "Dondurulmuş espresso", D: "Dondurmalı kahve" },
    correctOption: "B",
    difficulty: 2,
    funFact: "12-24 saat süren demleme daha yumuşak ve daha az asidik bir tat veriyor.",
  },
  {
    id: "tr_cafe_15",
    category: "☕ KAHVE & KAFE",
    text: "Dünya kahve üretimine hangi iki tür hâkimdir?",
    options: { A: "Arabica ve Robusta", B: "Mocha ve Latte", C: "Java ve Sumatra", D: "Bourbon ve Typica" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Robusta, Arabica'nın yaklaşık iki katı kafein içeriyor.",
  },
  {
    id: "tr_cafe_16",
    category: "☕ KAHVE & KAFE",
    text: "Latte art nedir?",
    options: { A: "Çekirdek dizilimi", B: "Süt köpüğüyle yapılan desen", C: "Boyalı fincan", D: "Bir kavurma yöntemi" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Kalp ve rozeta, latte art'ın iki temel figürü sayılıyor.",
  },
  {
    id: "tr_cafe_17",
    category: "☕ KAHVE & KAFE",
    text: "Hangi şehrin kahvehane kültürü UNESCO listesinde?",
    options: { A: "Paris", B: "Viyana", C: "Lizbon", D: "Prag" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Viyana kahvehane kültürü 2011'den beri somut olmayan kültürel miras listesinde.",
  },
  {
    id: "tr_cafe_18",
    category: "☕ KAHVE & KAFE",
    text: "En çok fermente edilen çay türü hangisidir?",
    options: { A: "Yeşil çay", B: "Beyaz çay", C: "Siyah çay", D: "Bitki çayı" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Çin'de siyah çaya, demin rengi yüzünden 'kırmızı çay' deniyor.",
  },
  {
    id: "tr_cafe_19",
    category: "☕ KAHVE & KAFE",
    text: "Süt neden protein içeriği sayesinde iyi köpürür?",
    options: { A: "Proteinler hava kabarcıklarını sabitler", B: "Yağ oranı düşüktür", C: "Şeker içerir", D: "Soğuk olduğu için" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Bitkisel içecekler bu yüzden çoğu zaman köpürmeyi destekleyen katkılar içeriyor.",
  },
  {
    id: "tr_music_10",
    category: "🎵 MÜZİK",
    text: "'The Dark Side of the Moon' albümü hangi gruba ait?",
    options: { A: "Led Zeppelin", B: "Pink Floyd", C: "The Doors", D: "Queen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Albüm ABD listelerinde 900 haftadan fazla kaldı.",
  },
  {
    id: "tr_music_11",
    category: "🎵 MÜZİK",
    text: "Klasik gitarda kaç tel vardır?",
    options: { A: "Dört", B: "Beş", C: "Altı", D: "Yedi" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Bas gitarda klasik olarak dört tel bulunur; karışıklık çoğu zaman buradan çıkıyor.",
  },
  {
    id: "tr_music_12",
    category: "🎵 MÜZİK",
    text: "Reggae müziği hangi ülkede doğmuştur?",
    options: { A: "Küba", B: "Jamaika", C: "Brezilya", D: "Trinidad" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Bob Marley'nin 'Exodus' albümü Time dergisi tarafından yüzyılın albümü seçildi.",
  },
  {
    id: "tr_music_13",
    category: "🎵 MÜZİK",
    text: "Standart bir piyanoda kaç tuş vardır?",
    options: { A: "76", B: "81", C: "88", D: "92" },
    correctOption: "C",
    difficulty: 2,
    funFact: "52 beyaz ve 36 siyah tuş toplamda tam 88 ediyor.",
  },
  {
    id: "tr_music_14",
    category: "🎵 MÜZİK",
    text: "Techno müziğin doğduğu şehir hangisidir?",
    options: { A: "Berlin", B: "Detroit", C: "Manchester", D: "Şikago" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Berlin sonradan Avrupa'nın techno başkenti oldu ama tür Detroit'te çıktı.",
  },
  {
    id: "tr_music_15",
    category: "🎵 MÜZİK",
    text: "Müzikte 'BPM' neyi ifade eder?",
    options: { A: "Ses yüksekliği", B: "Nota sayısı", C: "Dakikadaki vuruş", D: "Kanal sayısı" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Klasik house genelde 120-130 BPM aralığında.",
  },
  {
    id: "tr_music_16",
    category: "🎵 MÜZİK",
    text: "Hip-hop hangi bölgede ortaya çıktı?",
    options: { A: "Bronx", B: "Brooklyn", C: "Harlem", D: "Queens" },
    correctOption: "A",
    difficulty: 2,
    funFact: "DJ Kool Herc'in mahalle partileri hip-hop'ın başlangıcı sayılıyor.",
  },
  {
    id: "tr_music_17",
    category: "🎵 MÜZİK",
    text: "'A cappella' ne demektir?",
    options: { A: "Sadece piyanoyla", B: "Enstrümansız", C: "Sadece enstrümantal", D: "Orkestrayla" },
    correctOption: "B",
    difficulty: 1,
    funFact: "İtalyanca 'şapel usulü' anlamına geliyor.",
  },
  {
    id: "tr_cinema_10",
    category: "🎬 SİNEMA",
    text: "'Inception' filminin yönetmeni kimdir?",
    options: { A: "Ridley Scott", B: "Christopher Nolan", C: "Denis Villeneuve", D: "David Fincher" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Dönen koridor sahnesi bilgisayarla değil, gerçekten dönen bir sette çekildi.",
  },
  {
    id: "tr_cinema_11",
    category: "🎬 SİNEMA",
    text: "'Forrest Gump' filminde başrol kimdir?",
    options: { A: "Tom Hanks", B: "Tom Cruise", C: "Kevin Costner", D: "Robin Williams" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Tom Hanks üst üste iki yıl En İyi Erkek Oyuncu Oscar'ını kazandı.",
  },
  {
    id: "tr_cinema_12",
    category: "🎬 SİNEMA",
    text: "Sinemada 'cameo' ne demektir?",
    options: { A: "Senaryo hatası", B: "Çok kısa bir görünme", C: "Kamera hareketi", D: "Jenerik" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Alfred Hitchcock neredeyse bütün filmlerinde kısa bir görünme yapardı.",
  },
  {
    id: "tr_cinema_13",
    category: "🎬 SİNEMA",
    text: "'Game of Thrones' dizisi hangi kurgusal kıtada geçer?",
    options: { A: "Narnia", B: "Westeros", C: "Orta Dünya", D: "Panem" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Çekimler Kuzey İrlanda, Hırvatistan ve İzlanda'da yapıldı.",
  },
  {
    id: "tr_cinema_14",
    category: "🎬 SİNEMA",
    text: "'CGI' kısaltması neyi ifade eder?",
    options: { A: "Bilgisayarla üretilen görüntü", B: "Klasik film tekniği", C: "Kamera yönetimi", D: "Renk düzenleme" },
    correctOption: "A",
    difficulty: 2,
    funFact: "1982 yapımı 'Tron', yoğun CGI kullanan ilk filmlerden sayılıyor.",
  },
  {
    id: "tr_cinema_15",
    category: "🎬 SİNEMA",
    text: "Dünya çapında 2 milyar doları ilk aşan film hangisidir?",
    options: { A: "Titanic", B: "Avatar", C: "Avengers: Endgame", D: "Star Wars" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Titanic' bu eşiği 1998'de geçti; rekoru on bir yıl sonra 'Avatar' kırdı.",
  },
  {
    id: "tr_brain_10",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bir çiftçinin 17 koyunu var. Dokuzu hariç hepsi kaçıyor. Kaç koyun kalır?",
    options: { A: "8", B: "9", C: "17", D: "0" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Dokuzu hariç hepsi' ifadesi tam olarak dokuzunun kaldığı anlamına geliyor.",
  },
  {
    id: "tr_brain_11",
    category: "🧠 ZEKA TUZAĞI",
    text: "Kaç ay 28 gün çeker?",
    options: { A: "Bir", B: "İki", C: "On iki", D: "Hiçbiri" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Her ay en az 28 gün çeker; soruda 'tam olarak' denmiyor.",
  },
  {
    id: "tr_brain_12",
    category: "🧠 ZEKA TUZAĞI",
    text: "Kuruttukça ıslanan şey nedir?",
    options: { A: "Güneş", B: "Havlu", C: "Kâğıt", D: "Sünger" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Havlu başka şeyleri kuruturken kendisi suyu emiyor.",
  },
  {
    id: "tr_brain_13",
    category: "🧠 ZEKA TUZAĞI",
    text: "Üç kedi üç dakikada üç fare yakalıyorsa, 100 kedi 100 fareyi kaç dakikada yakalar?",
    options: { A: "Üç dakika", B: "100 dakika", C: "33 dakika", D: "Bir dakika" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Her kedi bir fareyi üç dakikada yakalıyor; sayıyı artırmak süreyi değiştirmiyor.",
  },
  {
    id: "tr_brain_14",
    category: "🧠 ZEKA TUZAĞI",
    text: "Boynu olup başı olmayan nedir?",
    options: { A: "Anahtar", B: "Şişe", C: "Ayakkabı", D: "Sandalye" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Gitar ve kemanın da boynu vardır ama başı yoktur.",
  },
  {
    id: "tr_brain_15",
    category: "🧠 ZEKA TUZAĞI",
    text: "100'den 10'u kaç kez çıkarabilirsiniz?",
    options: { A: "On kez", B: "Bir kez", C: "Dokuz kez", D: "Sonsuz" },
    correctOption: "B",
    difficulty: 2,
    funFact: "İlk çıkarmadan sonra sayı artık 100 değil, 90.",
  },
  {
    id: "tr_brain_16",
    category: "🧠 ZEKA TUZAĞI",
    text: "İki baba ve iki oğul balığa gidiyor, herkes bir balık tutuyor ama toplam üç balık var. Nasıl?",
    options: { A: "Biri hile yapıyor", B: "Dede, baba, oğul", C: "Bir balık kaçtı", D: "Birini paylaştılar" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ortadaki kişi hem baba hem oğul; üç kişi, dört rol.",
  },
  {
    id: "tr_gen_10",
    category: "🌍 GENEL KÜLTÜR",
    text: "Dünyanın en uzun kıyı şeridine sahip ülkesi hangisidir?",
    options: { A: "Rusya", B: "Kanada", C: "Avustralya", D: "Endonezya" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Kanada'nın kıyı şeridi 200.000 kilometreyi aşıyor; sebebi sayısız Arktik adası.",
  },
  {
    id: "tr_gen_11",
    category: "🌍 GENEL KÜLTÜR",
    text: "Avustralya'nın başkenti neresidir?",
    options: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Brisbane" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Canberra, Sidney ile Melbourne anlaşamayınca uzlaşma olarak inşa edildi.",
  },
  {
    id: "tr_gen_12",
    category: "🌍 GENEL KÜLTÜR",
    text: "Berlin Duvarı hangi yıl yıkıldı?",
    options: { A: "1987", B: "1989", C: "1990", D: "1991" },
    correctOption: "B",
    difficulty: 1,
    funFact: "9 Kasım 1989'daki sınır açılımı, yanlış anlaşılan bir basın toplantısının sonucuydu.",
  },
  {
    id: "tr_gen_13",
    category: "🌍 GENEL KÜLTÜR",
    text: "Ana dili en çok konuşulan dil hangisidir?",
    options: { A: "İngilizce", B: "İspanyolca", C: "Mandarin", D: "Hintçe" },
    correctOption: "C",
    difficulty: 2,
    funFact: "İngilizce ancak ikinci dil konuşanlar sayılınca başa geçiyor.",
  },
  {
    id: "tr_gen_14",
    category: "🌍 GENEL KÜLTÜR",
    text: "Dünyanın en büyük iç denizi hangisidir?",
    options: { A: "Karadeniz", B: "Hazar Denizi", C: "Baltık Denizi", D: "Ölü Deniz" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Hazar o kadar büyük ki göl mü deniz mi olduğu hâlâ tartışılıyor.",
  },
  {
    id: "tr_gen_15",
    category: "🌍 GENEL KÜLTÜR",
    text: "Karada en hızlı hayvan hangisidir?",
    options: { A: "Çita", B: "Antilop", C: "Aslan", D: "Deve kuşu" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Çita saatte 110 kilometreye ulaşıyor ama bu hızı yalnızca birkaç saniye koruyabiliyor.",
  },
  {
    id: "tr_gen_16",
    category: "🌍 GENEL KÜLTÜR",
    text: "En çok saat dilimine sahip ülke hangisidir?",
    options: { A: "Rusya", B: "ABD", C: "Çin", D: "Fransa" },
    correctOption: "D",
    difficulty: 3,
    funFact: "Denizaşırı toprakları sayesinde Fransa on iki saat dilimine yayılıyor.",
  },
  {
    id: "tr_gen_17",
    category: "🌍 GENEL KÜLTÜR",
    text: "Bir futbol maçında sahada takım başına kaç oyuncu bulunur?",
    options: { A: "Dokuz", B: "On", C: "On bir", D: "On iki" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Kaleci, kendi ceza sahasında topa elle dokunabilen tek oyuncudur.",
  },
  {
    id: "tr_sci_10",
    category: "🚀 BİLİM & TEKNO",
    text: "'Fe' hangi elementin simgesidir?",
    options: { A: "Flor", B: "Demir", C: "Kurşun", D: "Gümüş" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Fe', Latince 'ferrum' kelimesinden geliyor.",
  },
  {
    id: "tr_sci_11",
    category: "🚀 BİLİM & TEKNO",
    text: "Güneş ışığı Dünya'ya ne kadar sürede ulaşır?",
    options: { A: "8 saniye", B: "8 dakika", C: "8 saat", D: "8 gün" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Güneş'i her zaman sekiz dakika önceki hâliyle görüyoruz.",
  },
  {
    id: "tr_sci_12",
    category: "🚀 BİLİM & TEKNO",
    text: "İnsülin hangi organda üretilir?",
    options: { A: "Karaciğer", B: "Böbrek", C: "Pankreas", D: "Dalak" },
    correctOption: "C",
    difficulty: 2,
    funFact: "İnsülin 1921'de izole edildi ve diyabet tedavisini kökten değiştirdi.",
  },
  {
    id: "tr_sci_13",
    category: "🚀 BİLİM & TEKNO",
    text: "Bir byte kaç bitten oluşur?",
    options: { A: "Sekiz", B: "On", C: "Bir", D: "Bin" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Bir kilobyte teknik olarak 1024 byte; disk kapasitelerinin etikete uymamasının sebebi bu.",
  },
  {
    id: "tr_sci_14",
    category: "🚀 BİLİM & TEKNO",
    text: "Yetişkin bir insanda yaklaşık kaç kemik vardır?",
    options: { A: "106", B: "206", C: "306", D: "406" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Bebekler yaklaşık 300 kemikle doğuyor; büyürken birçoğu kaynaşıyor.",
  },
  {
    id: "tr_sci_15",
    category: "🚀 BİLİM & TEKNO",
    text: "Bitkiler fotosentezde hangi gazı alır?",
    options: { A: "Oksijen", B: "Azot", C: "Karbondioksit", D: "Hidrojen" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Karşılığında oksijen veriyorlar; bizim solunumumuzun tam tersi.",
  },
  {
    id: "tr_sci_16",
    category: "🚀 BİLİM & TEKNO",
    text: "Yazılımda 'açık kaynak' ne demektir?",
    options: { A: "Ücretsiz ama gizli", B: "Kaynak kodu herkese açık", C: "Sadece tarayıcıda çalışır", D: "İnternetsiz çalışır" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Linux en bilinen açık kaynak projesi ve dünyadaki sunucuların çoğunda çalışıyor.",
  },
  {
    id: "tr_sci_17",
    category: "🚀 BİLİM & TEKNO",
    text: "Güneş'e en yakın gezegen hangisidir?",
    options: { A: "Venüs", B: "Merkür", C: "Mars", D: "Dünya" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Buna rağmen en sıcak gezegen Venüs; sebebi yoğun atmosferi.",
  },
  {
    id: "tr_night_10",
    category: "🍸 GECE & KAFE",
    text: "'Mocktail' nedir?",
    options: { A: "Alkolsüz kokteyl", B: "Çift kokteyl", C: "Sıcak kokteyl", D: "Kahveli kokteyl" },
    correctOption: "A",
    difficulty: 1,
    funFact: "İsim, İngilizce 'mock' (taklit) ve 'cocktail' kelimelerinin birleşimi.",
  },
  {
    id: "tr_night_11",
    category: "🍸 GECE & KAFE",
    text: "Ayran neyden yapılır?",
    options: { A: "Yoğurt, su ve tuz", B: "Süt ve şeker", C: "Kefir ve bal", D: "Peynir suyu" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Ayran, Türkiye'de yemeğin yanında en çok tercih edilen içecek.",
  },
];

export const deQuestions: QuizQuestion[] = [
  // ─── NIGHTLIFE & CAFE ───
  {
    id: "de_night_1",
    category: "🍸 NACHTLEBEN",
    text: "Welches Kraut gibt einem Virgin Mojito seinen Charakter?",
    options: { A: "Basilikum", B: "Minze", C: "Thymian", D: "Rosmarin" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Minzblätter werden nur angedrückt, nicht zerstoßen – sonst werden sie bitter.",
  },
  {
    id: "de_night_2",
    category: "🍸 NACHTLEBEN",
    text: "Wie heißt die goldene Schaumschicht auf einem Espresso?",
    options: { A: "Sahne", B: "Crema", C: "Haube", D: "Schaumkrone" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Crema entsteht, wenn unter Druck gelöstes Kohlendioxid aus frischen Bohnen mit den Kaffeeölen aufschäumt – bei altem Kaffee bleibt sie fast aus.",
  },
  {
    id: "de_night_3",
    category: "🍸 NACHTLEBEN",
    text: "Was ist eine Kaffeebohne aus botanischer Sicht?",
    options: { A: "Baumrinde", B: "Samen einer Steinfrucht", C: "Wurzelknolle", D: "Blattknospe" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Kaffeebohnen sind eigentlich die Samen der roten Kaffeekirsche!",
  },

  // ─── MUSIK & POPKULTUR ───
  {
    id: "de_music_1",
    category: "🎵 MUSIK",
    text: "Welcher Song hat auf Spotify als erster aller Zeiten 3 Milliarden Streams erreicht?",
    options: { A: "Blinding Lights (The Weeknd)", B: "Shape of You (Ed Sheeran)", C: "Despacito (Luis Fonsi)", D: "Dance Monkey" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ed Sheerans Megahit knackte im Dezember 2021 als erster Track die 3-Milliarden-Marke.",
  },
  {
    id: "de_music_2",
    category: "🎵 MUSIK",
    text: "In welchem Jahr erschien der legendäre Queen-Hit 'Bohemian Rhapsody'?",
    options: { A: "1969", B: "1975", C: "1982", D: "1989" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Plattenfirma hielt den Song mit fast 6 Minuten anfangs für viel zu lang fürs Radio!",
  },

  // ─── KINO & SERIEN ───
  {
    id: "de_cinema_1",
    category: "🎬 KINO",
    text: "Welche Pille wählt Neo in 'Matrix', um die Wahrheit über die Welt zu erfahren?",
    options: { A: "Blau", B: "Rot", C: "Grün", D: "Gelb" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die rote Pille öffnet das Tor zur Realität, die blaue lässt einen in der Matrix weiterschlafen.",
  },
  {
    id: "de_cinema_2",
    category: "🎬 KINO",
    text: "Wo wurde der Eine Ring in 'Der Herr der Ringe' geschmiedet?",
    options: { A: "Schicksalsberg (Mount Doom)", B: "Erebor", C: "Nebelgebirge", D: "Isengart" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Der Ring kann nur dort zerstört werden, wo Sauron ihn einst geschmiedet hat.",
  },

  // ─── LOGIK & DENKSPORT ───
  {
    id: "de_brain_1",
    category: "🧠 DENKSPORT",
    text: "Wenn du in einem Rennen den Zweiten überholst, an welcher Position bist du dann?",
    options: { A: "Erster", B: "Zweiter", C: "Dritter", D: "Sieger" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Du übernimmst den Platz des Zweiten, der Erste ist immer noch vor dir!",
  },
  {
    id: "de_brain_2",
    category: "🧠 DENKSPORT",
    text: "Manche Monate haben 30 Tage, manche 31. Wie viele Monate haben 28 Tage?",
    options: { A: "1 (Februar)", B: "6", C: "Alle 12", D: "Keiner" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Jeder der 12 Monate hat mindestens 28 Tage!",
  },

  // ─── ALLGEMEINWISSEN ───
  {
    id: "de_gen_1",
    category: "🌍 WISSEN",
    text: "Was ist die Hauptstadt von Deutschland?",
    options: { A: "München", B: "Berlin", C: "Hamburg", D: "Frankfurt" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Berlin hat mehr Brücken als Venedig – insgesamt rund 960 Stück!",
  },
  {
    id: "de_gen_2",
    category: "🌍 WISSEN",
    text: "Welches chemische Element hat das Symbol 'Au' im Periodensystem?",
    options: { A: "Silber", B: "Gold", C: "Aluminium", D: "Kupfer" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Das Symbol leitet sich vom lateinischen Wort 'Aurum' (Morgenröte) ab.",
  },
  {
    id: "de_gen_3",
    category: "🌍 WISSEN",
    text: "In welchem Museum hängt das berühmte Gemälde 'Mona Lisa'?",
    options: { A: "British Museum", B: "Prado", C: "Louvre", D: "Uffizien" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Die Mona Lisa hat im Louvre einen eigenen Briefkasten für Liebesbriefe!",
  },
  {
    id: "de_gen_4",
    category: "🌍 WISSEN",
    text: "In welchem Jahr fiel die Berliner Mauer?",
    options: { A: "1989", B: "1990", C: "1991", D: "1988" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Der historische Mauerfall ereignete sich am Abend des 9. November 1989.",
  },

  // ─── WISSENSCHAFT & TECH ───
  {
    id: "de_sci_1",
    category: "🚀 WISSENSCHAFT",
    text: "Welcher Planet ist der heißeste in unserem Sonnensystem?",
    options: { A: "Merkur", B: "Venus", C: "Mars", D: "Jupiter" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Wegen des extremen Treibhauseffekts herrschen auf der Venus ca. 465°C!",
  },
  {
    id: "de_sci_2",
    category: "🚀 WISSENSCHAFT",
    text: "Wie viele Herzen hat ein Oktopus (Krake)?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Kraken haben 3 Herzen und ihr Blut ist durch Kupfer blau gefärbt!",
  },
  {
    id: "de_sci_3",
    category: "🚀 WISSENSCHAFT",
    text: "Wer gilt als die erste Computerprogrammiererin der Geschichte?",
    options: { A: "Alan Turing", B: "Ada Lovelace", C: "Marie Curie", D: "Grace Hopper" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Ada Lovelace verfasste bereits 1843 den ersten Algorithmus für eine Rechenmaschine.",
  },
  {
    id: "de_cafe_10",
    category: "☕ CAFÉ & KULTUR",
    text: "Aus welchem Land stammt die Kaffeepflanze ursprünglich?",
    options: { A: "Brasilien", B: "Äthiopien", C: "Kolumbien", D: "Jemen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Legende nach entdeckte ein Ziegenhirte namens Kaldi die Wirkung der Kaffeekirschen im äthiopischen Hochland.",
  },
  {
    id: "de_cafe_11",
    category: "☕ CAFÉ & KULTUR",
    text: "Was bedeutet 'Cappuccino' wörtlich übersetzt?",
    options: { A: "Kleine Kapuze", B: "Milchschaum", C: "Doppelter Kaffee", D: "Morgentrunk" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Der Name geht auf die Kapuzinermönche zurück – die Farbe ihrer Kutten erinnerte an den Kaffee mit Milch.",
  },
  {
    id: "de_cafe_12",
    category: "☕ CAFÉ & KULTUR",
    text: "Wie viele Espresso-Shots enthält ein klassischer Americano?",
    options: { A: "Keinen", B: "Einen oder zwei", C: "Genau vier", D: "Fünf" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Americano entstand, als US-Soldaten in Italien den Espresso mit heißem Wasser verdünnten.",
  },
  {
    id: "de_cafe_13",
    category: "☕ CAFÉ & KULTUR",
    text: "Welches Getränk besteht aus Espresso und einem Schuss Milchschaum?",
    options: { A: "Latte Macchiato", B: "Flat White", C: "Espresso Macchiato", D: "Mokka" },
    correctOption: "C",
    difficulty: 2,
    funFact: "'Macchiato' heißt 'gefleckt' – der Milchschaum hinterlässt einen Fleck auf dem Espresso.",
  },
  {
    id: "de_cafe_14",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche Teesorte wird am stärksten fermentiert?",
    options: { A: "Grüner Tee", B: "Weißer Tee", C: "Schwarzer Tee", D: "Kräutertee" },
    correctOption: "C",
    difficulty: 2,
    funFact: "In China heißt schwarzer Tee 'roter Tee' – nach der Farbe des Aufgusses, nicht der Blätter.",
  },
  {
    id: "de_cafe_15",
    category: "☕ CAFÉ & KULTUR",
    text: "Woraus wird Matcha hergestellt?",
    options: { A: "Gerösteten Reiskörnern", B: "Gemahlenen Grünteeblättern", C: "Getrockneten Minzblättern", D: "Fermentierten Kakaobohnen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Bei Matcha trinkt man das ganze Blatt mit – deshalb ist der Koffeingehalt höher als bei aufgegossenem Grüntee.",
  },
  {
    id: "de_cafe_16",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche Stadt ist für ihre traditionelle Kaffeehauskultur UNESCO-gelistet?",
    options: { A: "Paris", B: "Wien", C: "Lissabon", D: "Prag" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Wiener Kaffeehauskultur steht seit 2011 auf der UNESCO-Liste des immateriellen Kulturerbes.",
  },
  {
    id: "de_cafe_17",
    category: "☕ CAFÉ & KULTUR",
    text: "Was ist ein 'Flat White' im Vergleich zum Cappuccino?",
    options: { A: "Deutlich süßer", B: "Mit weniger, feinerem Milchschaum", C: "Ohne Espresso", D: "Immer kalt serviert" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Der Flat White kommt aus Australien und Neuseeland – beide Länder streiten bis heute über die Urheberschaft.",
  },
  {
    id: "de_cafe_18",
    category: "☕ CAFÉ & KULTUR",
    text: "Welches Gebäck wird traditionell zum Wiener Melange gereicht?",
    options: { A: "Croissant", B: "Bagel", C: "Kipferl", D: "Brezel" },
    correctOption: "C",
    difficulty: 3,
    funFact: "Das Kipferl gilt als Vorläufer des französischen Croissants.",
  },
  {
    id: "de_music_10",
    category: "🎵 MUSIK",
    text: "Welche Band veröffentlichte das Album 'The Dark Side of the Moon'?",
    options: { A: "Led Zeppelin", B: "Pink Floyd", C: "The Doors", D: "Queen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Das Album stand über 900 Wochen in den US-Charts – ein bis heute kaum gebrochener Rekord.",
  },
  {
    id: "de_music_11",
    category: "🎵 MUSIK",
    text: "Wie viele Saiten hat eine klassische Gitarre?",
    options: { A: "Vier", B: "Fünf", C: "Sechs", D: "Sieben" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Der Bass hat klassischerweise vier Saiten – deshalb verwechseln viele die beiden Instrumente beim Zählen.",
  },
  {
    id: "de_music_12",
    category: "🎵 MUSIK",
    text: "Aus welchem Land stammt der Musikstil Reggae?",
    options: { A: "Kuba", B: "Jamaika", C: "Brasilien", D: "Trinidad" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Bob Marleys 'Exodus' wurde vom Time Magazine zum Album des 20. Jahrhunderts gekürt.",
  },
  {
    id: "de_music_13",
    category: "🎵 MUSIK",
    text: "Welches Instrument spielte Miles Davis?",
    options: { A: "Saxofon", B: "Trompete", C: "Klavier", D: "Kontrabass" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Sein Album 'Kind of Blue' ist das meistverkaufte Jazzalbum aller Zeiten.",
  },
  {
    id: "de_music_14",
    category: "🎵 MUSIK",
    text: "Welche Stadt gilt als Geburtsort des Techno?",
    options: { A: "Berlin", B: "Detroit", C: "Manchester", D: "Chicago" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Berlin wurde später zur Techno-Hauptstadt Europas – erfunden wurde der Stil aber in Detroit.",
  },
  {
    id: "de_music_15",
    category: "🎵 MUSIK",
    text: "Wie viele Tasten hat ein Standard-Klavier?",
    options: { A: "76", B: "81", C: "88", D: "92" },
    correctOption: "C",
    difficulty: 2,
    funFact: "52 weiße und 36 schwarze Tasten ergeben zusammen genau 88.",
  },
  {
    id: "de_music_16",
    category: "🎵 MUSIK",
    text: "Welcher Komponist schrieb trotz zunehmender Taubheit weiter?",
    options: { A: "Mozart", B: "Beethoven", C: "Bach", D: "Chopin" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Seine 9. Sinfonie entstand, als er praktisch nichts mehr hören konnte.",
  },
  {
    id: "de_music_17",
    category: "🎵 MUSIK",
    text: "Was bezeichnet 'BPM' in der Musik?",
    options: { A: "Tonhöhe", B: "Lautstärke", C: "Schläge pro Minute", D: "Anzahl der Spuren" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Klassischer House liegt meist bei etwa 120–130 BPM.",
  },
  {
    id: "de_cinema_10",
    category: "🎬 KINO",
    text: "Welcher Film gewann als erster den Oscar für den besten Film?",
    options: { A: "Wings", B: "Metropolis", C: "Der Jazzsänger", D: "Nosferatu" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Wings' aus dem Jahr 1927 ist bis heute der einzige Stummfilm mit dieser Auszeichnung – neben 'The Artist' von 2011.",
  },
  {
    id: "de_cinema_11",
    category: "🎬 KINO",
    text: "Wer führte Regie bei 'Inception'?",
    options: { A: "Ridley Scott", B: "Christopher Nolan", C: "Denis Villeneuve", D: "David Fincher" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die berühmte sich drehende Flurszene wurde in einem real rotierenden Set gedreht, nicht am Computer.",
  },
  {
    id: "de_cinema_12",
    category: "🎬 KINO",
    text: "In welcher Stadt spielt der Film 'Lola rennt'?",
    options: { A: "Hamburg", B: "München", C: "Berlin", D: "Köln" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Der Film machte Franka Potente international bekannt und gilt als Meilenstein des deutschen Kinos der 90er.",
  },
  {
    id: "de_cinema_13",
    category: "🎬 KINO",
    text: "Welches Studio produzierte 'Der König der Löwen' von 1994?",
    options: { A: "Pixar", B: "Disney", C: "DreamWorks", D: "Warner Bros." },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Film war lange der erfolgreichste handgezeichnete Animationsfilm aller Zeiten.",
  },
  {
    id: "de_cinema_14",
    category: "🎬 KINO",
    text: "Welcher Schauspieler spielte in 'Das Leben der Anderen' den Stasi-Hauptmann?",
    options: { A: "Ulrich Mühe", B: "Bruno Ganz", C: "Moritz Bleibtreu", D: "Til Schweiger" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Der Film gewann 2007 den Oscar für den besten fremdsprachigen Film.",
  },
  {
    id: "de_cinema_15",
    category: "🎬 KINO",
    text: "Was ist ein 'Cameo' im Film?",
    options: { A: "Ein Drehbuchfehler", B: "Ein sehr kurzer Auftritt", C: "Eine Kamerafahrt", D: "Der Abspann" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Alfred Hitchcock hatte in fast allen seinen Filmen einen Cameo-Auftritt.",
  },
  {
    id: "de_brain_10",
    category: "🧠 DENKSPORT",
    text: "Ein Bauer hat 17 Schafe. Alle bis auf 9 laufen weg. Wie viele bleiben?",
    options: { A: "8", B: "9", C: "17", D: "0" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Alle bis auf 9' heißt: genau 9 bleiben übrig. Der Klassiker unter den Zahlenfallen.",
  },
  {
    id: "de_brain_11",
    category: "🧠 DENKSPORT",
    text: "Was wird nasser, je mehr es trocknet?",
    options: { A: "Die Sonne", B: "Ein Handtuch", C: "Ein Schwamm in der Sonne", D: "Papier" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ein Handtuch nimmt beim Trocknen anderer Dinge selbst Wasser auf.",
  },
  {
    id: "de_brain_12",
    category: "🧠 DENKSPORT",
    text: "Wie viele Monate haben 28 Tage?",
    options: { A: "Einer", B: "Zwei", C: "Alle zwölf", D: "Keiner" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Jeder Monat hat mindestens 28 Tage – gefragt war nicht 'genau 28'.",
  },
  {
    id: "de_brain_13",
    category: "🧠 DENKSPORT",
    text: "Ein Zug fährt nach Norden, der Wind weht nach Süden. Wohin zieht der Rauch?",
    options: { A: "Nach Norden", B: "Nach Süden", C: "Gar nicht, es ist ein E-Zug", D: "Nach Westen" },
    correctOption: "C",
    difficulty: 3,
    funFact: "Moderne Züge fahren elektrisch – kein Rauch, keine Richtung.",
  },
  {
    id: "de_brain_14",
    category: "🧠 DENKSPORT",
    text: "Was hat einen Hals, aber keinen Kopf?",
    options: { A: "Ein Schlüssel", B: "Eine Flasche", C: "Ein Schuh", D: "Ein Stuhl" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Auch Gitarren und Geigen haben einen Hals – aber ebenfalls keinen Kopf im Wortsinn.",
  },
  {
    id: "de_brain_15",
    category: "🧠 DENKSPORT",
    text: "Wenn drei Katzen in drei Minuten drei Mäuse fangen, wie lange brauchen 100 Katzen für 100 Mäuse?",
    options: { A: "Drei Minuten", B: "100 Minuten", C: "33 Minuten", D: "Eine Minute" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Jede Katze fängt eine Maus in drei Minuten – die Anzahl ändert daran nichts.",
  },
  {
    id: "de_brain_16",
    category: "🧠 DENKSPORT",
    text: "Was kann man fangen, aber nicht werfen?",
    options: { A: "Einen Ball", B: "Eine Erkältung", C: "Einen Stein", D: "Einen Blick" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Im Deutschen wie im Englischen 'fängt' man sich eine Erkältung ein.",
  },
  {
    id: "de_gen_10",
    category: "🌍 WISSEN",
    text: "Welches ist das größte Binnenmeer der Erde?",
    options: { A: "Schwarzes Meer", B: "Kaspisches Meer", C: "Ostsee", D: "Totes Meer" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Das Kaspische Meer ist so groß, dass bis heute gestritten wird, ob es ein See oder ein Meer ist.",
  },
  {
    id: "de_gen_11",
    category: "🌍 WISSEN",
    text: "Wie viele Bundesländer hat Deutschland?",
    options: { A: "14", B: "15", C: "16", D: "17" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Drei davon sind Stadtstaaten: Berlin, Hamburg und Bremen.",
  },
  {
    id: "de_gen_12",
    category: "🌍 WISSEN",
    text: "Welche Währung gilt in der Schweiz?",
    options: { A: "Euro", B: "Schweizer Franken", C: "Krone", D: "Schilling" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Schweiz ist von Euro-Ländern umgeben, hat den Euro aber nie eingeführt.",
  },
  {
    id: "de_gen_13",
    category: "🌍 WISSEN",
    text: "Welcher Fluss fließt durch Berlin?",
    options: { A: "Elbe", B: "Spree", C: "Oder", D: "Havel" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Spree mündet in Spandau in die Havel – beide fließen durch Berlin.",
  },
  {
    id: "de_gen_14",
    category: "🌍 WISSEN",
    text: "Welches Land hat die meisten Zeitzonen?",
    options: { A: "Russland", B: "USA", C: "China", D: "Frankreich" },
    correctOption: "D",
    difficulty: 3,
    funFact: "Durch seine Überseegebiete kommt Frankreich auf zwölf Zeitzonen – mehr als Russland.",
  },
  {
    id: "de_gen_15",
    category: "🌍 WISSEN",
    text: "Wie heißt die Hauptstadt von Australien?",
    options: { A: "Sydney", B: "Melbourne", C: "Canberra", D: "Brisbane" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Canberra wurde als Kompromiss gebaut, weil sich Sydney und Melbourne nicht einigen konnten.",
  },
  {
    id: "de_gen_16",
    category: "🌍 WISSEN",
    text: "Welches Tier ist das schnellste an Land?",
    options: { A: "Gepard", B: "Antilope", C: "Löwe", D: "Strauß" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Ein Gepard erreicht bis zu 110 km/h – hält das Tempo aber nur wenige Sekunden.",
  },
  {
    id: "de_gen_17",
    category: "🌍 WISSEN",
    text: "Wie viele Kontinente gibt es nach der gängigen deutschen Zählung?",
    options: { A: "Fünf", B: "Sechs", C: "Sieben", D: "Acht" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Je nach Land zählt man fünf, sechs oder sieben – eine reine Konventionsfrage.",
  },
  {
    id: "de_sci_10",
    category: "🚀 WISSENSCHAFT",
    text: "Welches Element hat das chemische Symbol 'Fe'?",
    options: { A: "Fluor", B: "Eisen", C: "Blei", D: "Silber" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Fe' kommt vom lateinischen 'ferrum'.",
  },
  {
    id: "de_sci_11",
    category: "🚀 WISSENSCHAFT",
    text: "Wie lange braucht das Licht von der Sonne zur Erde?",
    options: { A: "8 Sekunden", B: "8 Minuten", C: "8 Stunden", D: "8 Tage" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Wir sehen die Sonne immer so, wie sie vor gut acht Minuten aussah.",
  },
  {
    id: "de_sci_12",
    category: "🚀 WISSENSCHAFT",
    text: "Was misst ein Seismograf?",
    options: { A: "Luftdruck", B: "Erdbeben", C: "Luftfeuchtigkeit", D: "Schallpegel" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der erste bekannte Erdbebenmelder wurde im Jahr 132 in China gebaut.",
  },
  {
    id: "de_sci_13",
    category: "🚀 WISSENSCHAFT",
    text: "Welches Organ produziert Insulin?",
    options: { A: "Leber", B: "Niere", C: "Bauchspeicheldrüse", D: "Milz" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Insulin wurde 1921 entdeckt und veränderte die Behandlung von Diabetes grundlegend.",
  },
  {
    id: "de_sci_14",
    category: "🚀 WISSENSCHAFT",
    text: "Wofür steht 'KI' in der Technik?",
    options: { A: "Kinetische Induktion", B: "Künstliche Intelligenz", C: "Kritischer Index", D: "Kalte Ionisation" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der englische Begriff 'Artificial Intelligence' wurde 1956 auf einer Konferenz in Dartmouth geprägt.",
  },
  {
    id: "de_sci_15",
    category: "🚀 WISSENSCHAFT",
    text: "Welcher Planet ist der Sonne am nächsten?",
    options: { A: "Venus", B: "Merkur", C: "Mars", D: "Erde" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Trotz der Nähe zur Sonne ist die Venus der heißeste Planet – wegen ihrer dichten Atmosphäre.",
  },
  {
    id: "de_sci_16",
    category: "🚀 WISSENSCHAFT",
    text: "Was bezeichnet der Begriff 'Byte'?",
    options: { A: "Acht Bit", B: "Zehn Bit", C: "Ein Bit", D: "Tausend Bit" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Ein Kilobyte sind technisch 1024 Byte, nicht 1000 – daher stimmen Festplattenangaben oft nicht mit der Anzeige überein.",
  },
  {
    id: "de_night_10",
    category: "🍸 NACHTLEBEN",
    text: "Was ist ein 'Mocktail'?",
    options: { A: "Ein Cocktail ohne Alkohol", B: "Ein doppelter Cocktail", C: "Ein warmer Cocktail", D: "Ein Cocktail mit Kaffee" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Der Name ist ein Wortspiel aus 'mock' (nachgemacht) und 'Cocktail'.",
  },
  {
    id: "de_night_11",
    category: "🍸 NACHTLEBEN",
    text: "Welche Frucht gehört klassisch in eine Limonade?",
    options: { A: "Zitrone", B: "Ananas", C: "Banane", D: "Kirsche" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Das Wort 'Limonade' geht auf das persische 'limun' für Zitrone zurück.",
  },
  {
    id: "de_night_12",
    category: "🍸 NACHTLEBEN",
    text: "Was ist Ayran?",
    options: { A: "Ein Joghurtgetränk", B: "Ein Fruchtsaft", C: "Ein Kräutertee", D: "Ein Gebäck" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Ayran wird aus Joghurt, Wasser und Salz gemixt und ist in der Türkei das Standardgetränk zum Essen.",
  },
  {
    id: "de_cafe_20",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche Milch schäumt wegen ihres Proteingehalts am besten?",
    options: { A: "Vollmilch", B: "Reismilch", C: "Kokosmilch", D: "Mandelmilch" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Beim Aufschäumen stabilisieren Milchproteine die Luftbläschen – Pflanzendrinks brauchen dafür oft Zusätze.",
  },
  {
    id: "de_cafe_21",
    category: "☕ CAFÉ & KULTUR",
    text: "Was ist 'Cold Brew'?",
    options: { A: "Heiß gebrühter, dann gekühlter Kaffee", B: "Kalt extrahierter Kaffee", C: "Kaffee mit Eiscreme", D: "Gefrorener Espresso" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Extraktion dauert 12 bis 24 Stunden – das Ergebnis schmeckt milder und weniger sauer.",
  },
  {
    id: "de_cafe_22",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche zwei Kaffeearten dominieren den Weltmarkt?",
    options: { A: "Arabica und Robusta", B: "Mokka und Latte", C: "Java und Sumatra", D: "Bourbon und Typica" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Robusta enthält etwa doppelt so viel Koffein wie Arabica.",
  },
  {
    id: "de_cafe_23",
    category: "☕ CAFÉ & KULTUR",
    text: "Welches Land trinkt pro Kopf am meisten Kaffee?",
    options: { A: "Italien", B: "Finnland", C: "Brasilien", D: "Türkei" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Finnland liegt seit Jahren an der Spitze – mit deutlich über acht Kilogramm pro Kopf und Jahr.",
  },
  {
    id: "de_cafe_24",
    category: "☕ CAFÉ & KULTUR",
    text: "Wie wird türkischer Kaffee traditionell zubereitet?",
    options: { A: "Mit einer Filtermaschine", B: "In einem Kupferkännchen", C: "Mit einer Presse", D: "Im Wasserkocher" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Das Kännchen heißt Cezve; der Kaffeesatz bleibt in der Tasse und wird traditionell gedeutet.",
  },
  {
    id: "de_cafe_25",
    category: "☕ CAFÉ & KULTUR",
    text: "Was ist Latte Art?",
    options: { A: "Ein Kaffeebohnen-Muster", B: "Muster im Milchschaum", C: "Bemalte Tassen", D: "Eine Röstmethode" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Herz und Rosetta gelten als die beiden Grundfiguren jeder Latte Art.",
  },
  {
    id: "de_music_20",
    category: "🎵 MUSIK",
    text: "Welcher Künstler veröffentlichte das Album '25'?",
    options: { A: "Adele", B: "Beyoncé", C: "Rihanna", D: "Taylor Swift" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Adele benennt ihre Alben nach ihrem Alter während des Entstehungsprozesses.",
  },
  {
    id: "de_music_21",
    category: "🎵 MUSIK",
    text: "Welches Genre entstand in den 1970ern in der Bronx?",
    options: { A: "Hip-Hop", B: "Punk", C: "Disco", D: "Soul" },
    correctOption: "A",
    difficulty: 2,
    funFact: "DJ Kool Hercs Blockpartys gelten als Geburtsstunde des Hip-Hop.",
  },
  {
    id: "de_music_22",
    category: "🎵 MUSIK",
    text: "Wie viele Musiker hatten die Beatles in ihrer bekanntesten Besetzung?",
    options: { A: "Drei", B: "Vier", C: "Fünf", D: "Sechs" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Vor Ringo Starr saß Pete Best am Schlagzeug – er verließ die Band kurz vor dem Durchbruch.",
  },
  {
    id: "de_music_23",
    category: "🎵 MUSIK",
    text: "Was ist ein 'A cappella'-Stück?",
    options: { A: "Nur mit Klavier", B: "Ohne Instrumente", C: "Nur instrumental", D: "Mit Orchester" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Begriff kommt aus dem Italienischen und bedeutet 'nach Art der Kapelle'.",
  },
  {
    id: "de_cinema_20",
    category: "🎬 KINO",
    text: "Welcher Film spielte als erster weltweit über zwei Milliarden Dollar ein?",
    options: { A: "Titanic", B: "Avatar", C: "Avengers: Endgame", D: "Star Wars" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Titanic' knackte die Marke 1998 – erst 'Avatar' übertraf den Rekord elf Jahre später.",
  },
  {
    id: "de_cinema_21",
    category: "🎬 KINO",
    text: "Welche Serie spielt im fiktiven Königreich Westeros?",
    options: { A: "The Witcher", B: "Game of Thrones", C: "Vikings", D: "The Crown" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Serie wurde unter anderem in Nordirland, Kroatien und Island gedreht.",
  },
  {
    id: "de_cinema_22",
    category: "🎬 KINO",
    text: "Wer spielte die Hauptrolle in 'Forrest Gump'?",
    options: { A: "Tom Hanks", B: "Tom Cruise", C: "Kevin Costner", D: "Robin Williams" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Tom Hanks gewann in zwei aufeinanderfolgenden Jahren den Oscar als bester Hauptdarsteller.",
  },
  {
    id: "de_cinema_23",
    category: "🎬 KINO",
    text: "Was bedeutet die Abkürzung 'CGI'?",
    options: { A: "Computergenerierte Bilder", B: "Klassische Filmtechnik", C: "Kameraführung", D: "Farbkorrektur" },
    correctOption: "A",
    difficulty: 2,
    funFact: "'Tron' von 1982 gilt als einer der ersten Filme mit umfangreichem CGI-Einsatz.",
  },
  {
    id: "de_brain_20",
    category: "🧠 DENKSPORT",
    text: "Wie oft kann man 10 von 100 abziehen?",
    options: { A: "Zehnmal", B: "Einmal", C: "Neunmal", D: "Unendlich oft" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Nach dem ersten Abziehen ist es nicht mehr 100, sondern 90.",
  },
  {
    id: "de_brain_21",
    category: "🧠 DENKSPORT",
    text: "Zwei Väter und zwei Söhne gehen angeln, jeder fängt einen Fisch. Es sind nur drei Fische. Wie geht das?",
    options: { A: "Einer schummelt", B: "Großvater, Vater, Sohn", C: "Ein Fisch entkam", D: "Sie teilen sich einen" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Der mittlere ist gleichzeitig Vater und Sohn – drei Personen, vier Rollen.",
  },
  {
    id: "de_brain_22",
    category: "🧠 DENKSPORT",
    text: "Was geht hoch und kommt nie wieder herunter?",
    options: { A: "Ein Ballon", B: "Das Alter", C: "Der Rauch", D: "Ein Pfeil" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ein Rätsel, das in fast jeder Sprache existiert.",
  },
  {
    id: "de_gen_20",
    category: "🌍 WISSEN",
    text: "Welches Land hat die längste Küstenlinie der Welt?",
    options: { A: "Russland", B: "Kanada", C: "Australien", D: "Indonesien" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Kanadas Küstenlinie ist über 200.000 Kilometer lang – wegen der unzähligen arktischen Inseln.",
  },
  {
    id: "de_gen_21",
    category: "🌍 WISSEN",
    text: "Wie viele Spieler stehen bei einem Fußballspiel pro Mannschaft auf dem Feld?",
    options: { A: "Neun", B: "Zehn", C: "Elf", D: "Zwölf" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Der Torwart ist der einzige Feldspieler, der den Ball im eigenen Strafraum mit der Hand berühren darf.",
  },
  {
    id: "de_gen_22",
    category: "🌍 WISSEN",
    text: "Welche Sprache hat weltweit die meisten Muttersprachler?",
    options: { A: "Englisch", B: "Spanisch", C: "Mandarin", D: "Hindi" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Englisch führt erst, wenn man Zweitsprachler mitzählt.",
  },
  {
    id: "de_sci_20",
    category: "🚀 WISSENSCHAFT",
    text: "Was ist die häufigste Substanz im menschlichen Körper?",
    options: { A: "Eiweiß", B: "Wasser", C: "Fett", D: "Kalzium" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Etwa 60 Prozent des Körpergewichts eines Erwachsenen bestehen aus Wasser.",
  },
  {
    id: "de_sci_21",
    category: "🚀 WISSENSCHAFT",
    text: "Welches Gas atmen Pflanzen bei der Fotosynthese auf?",
    options: { A: "Sauerstoff", B: "Stickstoff", C: "Kohlendioxid", D: "Wasserstoff" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Sie geben dabei Sauerstoff ab – genau umgekehrt zu unserer Atmung.",
  },
  {
    id: "de_sci_22",
    category: "🚀 WISSENSCHAFT",
    text: "Wie viele Knochen hat ein erwachsener Mensch etwa?",
    options: { A: "106", B: "206", C: "306", D: "406" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Babys kommen mit rund 300 Knochen zur Welt – viele verwachsen im Laufe des Wachstums.",
  },
  {
    id: "de_sci_23",
    category: "🚀 WISSENSCHAFT",
    text: "Was bedeutet 'Open Source' bei Software?",
    options: { A: "Kostenlos, aber geheim", B: "Quellcode ist öffentlich einsehbar", C: "Nur im Browser nutzbar", D: "Ohne Internet nutzbar" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Linux ist das bekannteste Open-Source-Projekt und läuft auf den meisten Servern weltweit.",
  },
  {
    id: "de_gen_24",
    category: "🌍 WISSEN",
    text: "Welches Meer grenzt im Norden an Deutschland?",
    options: { A: "Nur die Nordsee", B: "Nordsee und Ostsee", C: "Nur die Ostsee", D: "Das Mittelmeer" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Schleswig-Holstein ist das einzige Bundesland mit Küste an beiden Meeren.",
  },
];

export const enQuestions: QuizQuestion[] = [
  // ─── NIGHTLIFE & CAFE ───
  {
    id: "en_night_1",
    category: "🍸 NIGHTLIFE",
    text: "Which herb gives a virgin mojito its character?",
    options: { A: "Basil", B: "Mint", C: "Thyme", D: "Rosemary" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Mint leaves should be pressed gently, not crushed — crushing turns them bitter.",
  },
  {
    id: "en_night_2",
    category: "🍸 NIGHTLIFE",
    text: "What is the golden foam layer on top of an espresso called?",
    options: { A: "Cream", B: "Crema", C: "Head", D: "Froth" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Crema forms when carbon dioxide from fresh beans emulsifies with the coffee oils under pressure; stale beans produce almost none.",
  },

  // ─── MUSIC & POP CULTURE ───
  {
    id: "en_music_1",
    category: "🎵 MUSIC",
    text: "Which song was the first in Spotify history to surpass 3 billion streams?",
    options: { A: "Blinding Lights", B: "Shape of You", C: "Despacito", D: "Starboy" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ed Sheeran's 'Shape of You' crossed 3 billion streams in December 2021.",
  },
  {
    id: "en_music_2",
    category: "🎵 MUSIC",
    text: "What year was Queen's iconic 'Bohemian Rhapsody' released?",
    options: { A: "1969", B: "1975", C: "1982", D: "1989" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Record executives initially thought the 6-minute operatic track would never work on radio!",
  },

  // ─── CINEMA & TV ───
  {
    id: "en_cinema_1",
    category: "🎬 MOVIES",
    text: "In 'The Matrix', which pill does Neo take to see the real world?",
    options: { A: "Blue Pill", B: "Red Pill", C: "Green Pill", D: "Yellow Pill" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The red pill represents truth and reality, while the blue pill maintains the illusion.",
  },
  {
    id: "en_cinema_2",
    category: "🎬 MOVIES",
    text: "Where was the One Ring forged in 'The Lord of the Rings'?",
    options: { A: "Mount Doom", B: "The Lonely Mountain", C: "Misty Mountains", D: "Isengard" },
    correctOption: "A",
    difficulty: 1,
    funFact: "The One Ring could only be unmade in the fires of Mount Doom where it was forged.",
  },

  // ─── BRAIN TEASERS ───
  {
    id: "en_brain_1",
    category: "🧠 BRAIN TEASER",
    text: "If you overtake the second person in a race, what position are you in?",
    options: { A: "1st", B: "2nd", C: "3rd", D: "Winner" },
    correctOption: "B",
    difficulty: 1,
    funFact: "You take the place of the person in 2nd; the person in 1st is still ahead of you!",
  },
  {
    id: "en_brain_2",
    category: "🧠 BRAIN TEASER",
    text: "Some months have 30 days, some have 31. How many months have 28 days?",
    options: { A: "1 (February)", B: "6", C: "All 12", D: "None" },
    correctOption: "C",
    difficulty: 2,
    funFact: "All 12 months have at least 28 days!",
  },

  // ─── GENERAL KNOWLEDGE ───
  {
    id: "en_gen_1",
    category: "🌍 TRIVIA",
    text: "Which chemical element is represented by the symbol 'Au'?",
    options: { A: "Silver", B: "Gold", C: "Aluminum", D: "Copper" },
    correctOption: "B",
    difficulty: 1,
    funFact: "'Au' comes from the Latin word 'Aurum', meaning 'shining dawn'.",
  },
  {
    id: "en_gen_2",
    category: "🌍 TRIVIA",
    text: "In which museum is the Mona Lisa currently displayed?",
    options: { A: "The British Museum", B: "The Prado", C: "The Louvre", D: "The Met" },
    correctOption: "C",
    difficulty: 1,
    funFact: "The Mona Lisa has her own mailbox at the Louvre and receives love letters every year!",
  },

  // ─── SCIENCE & TECH ───
  {
    id: "en_sci_1",
    category: "🚀 SCIENCE",
    text: "Which planet is the hottest in our solar system?",
    options: { A: "Mercury", B: "Venus", C: "Mars", D: "Jupiter" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Due to its thick carbon dioxide atmosphere and runaway greenhouse effect, Venus reaches 465°C!",
  },
  {
    id: "en_sci_2",
    category: "🚀 SCIENCE",
    text: "How many hearts does an octopus have?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Octopuses have 3 hearts and blue copper-based blood!",
  },
  {
    id: "en_sci_3",
    category: "🚀 SCIENCE",
    text: "Who is widely considered the world's first computer programmer?",
    options: { A: "Alan Turing", B: "Ada Lovelace", C: "Charles Babbage", D: "Grace Hopper" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Ada Lovelace wrote the very first algorithm intended for Babbage's Analytical Engine in 1843.",
  },
  {
    id: "en_cafe_10",
    category: "☕ CAFÉ & CULTURE",
    text: "Which country is the original home of the coffee plant?",
    options: { A: "Brazil", B: "Ethiopia", C: "Colombia", D: "Yemen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Legend credits a goat herder named Kaldi with noticing how the coffee cherries energised his goats.",
  },
  {
    id: "en_cafe_11",
    category: "☕ CAFÉ & CULTURE",
    text: "What does 'macchiato' mean in Italian?",
    options: { A: "Stained", B: "Strong", C: "Sweet", D: "Layered" },
    correctOption: "A",
    difficulty: 2,
    funFact: "The foam leaves a 'stain' on the espresso — hence the name.",
  },
  {
    id: "en_cafe_12",
    category: "☕ CAFÉ & CULTURE",
    text: "What is cold brew coffee?",
    options: { A: "Hot coffee poured over ice", B: "Coffee extracted with cold water over many hours", C: "Frozen espresso", D: "Coffee with ice cream" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Steeping for 12 to 24 hours produces a smoother, less acidic cup.",
  },
  {
    id: "en_cafe_13",
    category: "☕ CAFÉ & CULTURE",
    text: "Which two coffee species dominate world production?",
    options: { A: "Arabica and Robusta", B: "Mocha and Latte", C: "Java and Sumatra", D: "Bourbon and Typica" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Robusta carries roughly twice the caffeine of Arabica.",
  },
  {
    id: "en_cafe_14",
    category: "☕ CAFÉ & CULTURE",
    text: "What is matcha made from?",
    options: { A: "Roasted rice", B: "Ground green tea leaves", C: "Dried mint", D: "Fermented cocoa" },
    correctOption: "B",
    difficulty: 1,
    funFact: "You drink the whole leaf, which is why matcha has more caffeine than steeped green tea.",
  },
  {
    id: "en_cafe_15",
    category: "☕ CAFÉ & CULTURE",
    text: "Which city's coffee house culture is on the UNESCO heritage list?",
    options: { A: "Paris", B: "Vienna", C: "Lisbon", D: "Istanbul" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Viennese coffee house culture was inscribed in 2011 as intangible cultural heritage.",
  },
  {
    id: "en_cafe_16",
    category: "☕ CAFÉ & CULTURE",
    text: "How does a flat white differ from a cappuccino?",
    options: { A: "It is sweeter", B: "It has less, finer foam", C: "It has no espresso", D: "It is always iced" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Australia and New Zealand still argue over which country invented it.",
  },
  {
    id: "en_cafe_17",
    category: "☕ CAFÉ & CULTURE",
    text: "Which tea is the most heavily oxidised?",
    options: { A: "Green tea", B: "White tea", C: "Black tea", D: "Herbal tea" },
    correctOption: "C",
    difficulty: 2,
    funFact: "In China it is called 'red tea', after the colour of the liquid rather than the leaf.",
  },
  {
    id: "en_cafe_18",
    category: "☕ CAFÉ & CULTURE",
    text: "What is a mocktail?",
    options: { A: "A cocktail without alcohol", B: "A double cocktail", C: "A hot cocktail", D: "A coffee cocktail" },
    correctOption: "A",
    difficulty: 1,
    funFact: "The name is a play on 'mock' and 'cocktail'.",
  },
  {
    id: "en_music_10",
    category: "🎵 MUSIC",
    text: "Which band released 'The Dark Side of the Moon'?",
    options: { A: "Led Zeppelin", B: "Pink Floyd", C: "The Doors", D: "Queen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "It spent more than 900 weeks on the US charts.",
  },
  {
    id: "en_music_11",
    category: "🎵 MUSIC",
    text: "Which city is considered the birthplace of techno?",
    options: { A: "Berlin", B: "Detroit", C: "Manchester", D: "Chicago" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Berlin later became Europe's techno capital, but the sound started in Detroit.",
  },
  {
    id: "en_music_12",
    category: "🎵 MUSIC",
    text: "How many keys does a standard piano have?",
    options: { A: "76", B: "81", C: "88", D: "92" },
    correctOption: "C",
    difficulty: 2,
    funFact: "52 white keys plus 36 black ones make exactly 88.",
  },
  {
    id: "en_music_13",
    category: "🎵 MUSIC",
    text: "Which instrument did Miles Davis play?",
    options: { A: "Saxophone", B: "Trumpet", C: "Piano", D: "Double bass" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Kind of Blue' is the best-selling jazz album of all time.",
  },
  {
    id: "en_music_14",
    category: "🎵 MUSIC",
    text: "What does BPM measure in music?",
    options: { A: "Pitch", B: "Volume", C: "Beats per minute", D: "Track count" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Classic house usually sits around 120 to 130 BPM.",
  },
  {
    id: "en_music_15",
    category: "🎵 MUSIC",
    text: "Which genre emerged in the Bronx in the 1970s?",
    options: { A: "Hip-hop", B: "Punk", C: "Disco", D: "Soul" },
    correctOption: "A",
    difficulty: 2,
    funFact: "DJ Kool Herc's block parties are widely seen as the starting point.",
  },
  {
    id: "en_music_16",
    category: "🎵 MUSIC",
    text: "What does 'a cappella' mean?",
    options: { A: "With piano only", B: "Without instruments", C: "Instrumental only", D: "With an orchestra" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The Italian phrase means 'in the manner of the chapel'.",
  },
  {
    id: "en_cinema_10",
    category: "🎬 MOVIES",
    text: "Who directed 'Inception'?",
    options: { A: "Ridley Scott", B: "Christopher Nolan", C: "Denis Villeneuve", D: "David Fincher" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The rotating corridor fight was filmed on a real spinning set, not with CGI.",
  },
  {
    id: "en_cinema_11",
    category: "🎬 MOVIES",
    text: "Which fictional kingdom is the setting of 'Game of Thrones'?",
    options: { A: "Narnia", B: "Westeros", C: "Middle-earth", D: "Panem" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Filming took place in Northern Ireland, Croatia and Iceland among others.",
  },
  {
    id: "en_cinema_12",
    category: "🎬 MOVIES",
    text: "Who starred as the title character in 'Forrest Gump'?",
    options: { A: "Tom Hanks", B: "Tom Cruise", C: "Kevin Costner", D: "Robin Williams" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Hanks won the Best Actor Oscar two years running.",
  },
  {
    id: "en_cinema_13",
    category: "🎬 MOVIES",
    text: "What is a cameo in film?",
    options: { A: "A scripting error", B: "A very brief appearance", C: "A camera move", D: "The closing credits" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Alfred Hitchcock appeared in almost all of his own films.",
  },
  {
    id: "en_cinema_14",
    category: "🎬 MOVIES",
    text: "Which film was the first to gross over two billion dollars worldwide?",
    options: { A: "Titanic", B: "Avatar", C: "Avengers: Endgame", D: "Star Wars" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Titanic' passed the mark in 1998; 'Avatar' beat the record eleven years later.",
  },
  {
    id: "en_cinema_15",
    category: "🎬 MOVIES",
    text: "What does CGI stand for?",
    options: { A: "Computer-generated imagery", B: "Classic guided input", C: "Central grading interface", D: "Colour grading index" },
    correctOption: "A",
    difficulty: 2,
    funFact: "'Tron' from 1982 is often cited as one of the first films with extensive CGI.",
  },
  {
    id: "en_brain_10",
    category: "🧠 BRAIN TEASER",
    text: "A farmer has 17 sheep. All but 9 run away. How many are left?",
    options: { A: "8", B: "9", C: "17", D: "0" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'All but 9' means exactly 9 stay. A classic number trap.",
  },
  {
    id: "en_brain_11",
    category: "🧠 BRAIN TEASER",
    text: "How many months have 28 days?",
    options: { A: "One", B: "Two", C: "All twelve", D: "None" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Every month has at least 28 days — the question never said 'exactly'.",
  },
  {
    id: "en_brain_12",
    category: "🧠 BRAIN TEASER",
    text: "What gets wetter the more it dries?",
    options: { A: "The sun", B: "A towel", C: "Paper", D: "A sponge" },
    correctOption: "B",
    difficulty: 2,
    funFact: "A towel soaks up water as it dries everything else.",
  },
  {
    id: "en_brain_13",
    category: "🧠 BRAIN TEASER",
    text: "If three cats catch three mice in three minutes, how long do 100 cats need for 100 mice?",
    options: { A: "Three minutes", B: "100 minutes", C: "33 minutes", D: "One minute" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Each cat takes three minutes per mouse; scaling up changes nothing.",
  },
  {
    id: "en_brain_14",
    category: "🧠 BRAIN TEASER",
    text: "What has a neck but no head?",
    options: { A: "A key", B: "A bottle", C: "A shoe", D: "A chair" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Guitars and violins have necks too — and also no heads.",
  },
  {
    id: "en_brain_15",
    category: "🧠 BRAIN TEASER",
    text: "How many times can you subtract 10 from 100?",
    options: { A: "Ten times", B: "Once", C: "Nine times", D: "Infinitely" },
    correctOption: "B",
    difficulty: 2,
    funFact: "After the first subtraction it is no longer 100, it is 90.",
  },
  {
    id: "en_brain_16",
    category: "🧠 BRAIN TEASER",
    text: "What goes up and never comes back down?",
    options: { A: "A balloon", B: "Your age", C: "Smoke", D: "An arrow" },
    correctOption: "B",
    difficulty: 2,
    funFact: "A riddle that exists in almost every language.",
  },
  {
    id: "en_gen_10",
    category: "🌍 TRIVIA",
    text: "Which country has the longest coastline in the world?",
    options: { A: "Russia", B: "Canada", C: "Australia", D: "Indonesia" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Canada's coastline runs over 200,000 kilometres thanks to its Arctic islands.",
  },
  {
    id: "en_gen_11",
    category: "🌍 TRIVIA",
    text: "What is the capital of Australia?",
    options: { A: "Sydney", B: "Melbourne", C: "Canberra", D: "Brisbane" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Canberra was purpose-built as a compromise between Sydney and Melbourne.",
  },
  {
    id: "en_gen_12",
    category: "🌍 TRIVIA",
    text: "Which language has the most native speakers?",
    options: { A: "English", B: "Spanish", C: "Mandarin", D: "Hindi" },
    correctOption: "C",
    difficulty: 2,
    funFact: "English only takes the lead once second-language speakers are counted.",
  },
  {
    id: "en_gen_13",
    category: "🌍 TRIVIA",
    text: "In which year did the Berlin Wall fall?",
    options: { A: "1987", B: "1989", C: "1990", D: "1991" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The border opened on 9 November 1989 after a garbled press conference.",
  },
  {
    id: "en_gen_14",
    category: "🌍 TRIVIA",
    text: "Which country has the most time zones?",
    options: { A: "Russia", B: "USA", C: "China", D: "France" },
    correctOption: "D",
    difficulty: 3,
    funFact: "Counting its overseas territories, France spans twelve time zones.",
  },
  {
    id: "en_gen_15",
    category: "🌍 TRIVIA",
    text: "What is the largest inland body of water on Earth?",
    options: { A: "Black Sea", B: "Caspian Sea", C: "Lake Superior", D: "Dead Sea" },
    correctOption: "B",
    difficulty: 2,
    funFact: "It is so large that people still argue whether it is a lake or a sea.",
  },
  {
    id: "en_gen_16",
    category: "🌍 TRIVIA",
    text: "Which animal is the fastest on land?",
    options: { A: "Cheetah", B: "Antelope", C: "Lion", D: "Ostrich" },
    correctOption: "A",
    difficulty: 1,
    funFact: "A cheetah hits about 110 km/h but can only hold it for a few seconds.",
  },
  {
    id: "en_gen_17",
    category: "🌍 TRIVIA",
    text: "How many players per team are on the pitch in football?",
    options: { A: "Nine", B: "Ten", C: "Eleven", D: "Twelve" },
    correctOption: "C",
    difficulty: 1,
    funFact: "The goalkeeper is the only one allowed to handle the ball inside their own penalty area.",
  },
  {
    id: "en_sci_10",
    category: "🚀 SCIENCE",
    text: "Which element has the symbol 'Fe'?",
    options: { A: "Fluorine", B: "Iron", C: "Lead", D: "Silver" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Fe' comes from the Latin 'ferrum'.",
  },
  {
    id: "en_sci_11",
    category: "🚀 SCIENCE",
    text: "How long does sunlight take to reach Earth?",
    options: { A: "8 seconds", B: "8 minutes", C: "8 hours", D: "8 days" },
    correctOption: "B",
    difficulty: 2,
    funFact: "We always see the sun as it looked about eight minutes ago.",
  },
  {
    id: "en_sci_12",
    category: "🚀 SCIENCE",
    text: "Which organ produces insulin?",
    options: { A: "Liver", B: "Kidney", C: "Pancreas", D: "Spleen" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Insulin was isolated in 1921 and transformed diabetes treatment.",
  },
  {
    id: "en_sci_13",
    category: "🚀 SCIENCE",
    text: "Which planet is closest to the sun?",
    options: { A: "Venus", B: "Mercury", C: "Mars", D: "Earth" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Venus is still the hottest planet, thanks to its thick atmosphere.",
  },
  {
    id: "en_sci_14",
    category: "🚀 SCIENCE",
    text: "How many bits are in a byte?",
    options: { A: "Eight", B: "Ten", C: "One", D: "A thousand" },
    correctOption: "A",
    difficulty: 2,
    funFact: "A kilobyte is technically 1024 bytes, which is why drive sizes never quite match the label.",
  },
  {
    id: "en_sci_15",
    category: "🚀 SCIENCE",
    text: "Roughly how many bones does an adult human have?",
    options: { A: "106", B: "206", C: "306", D: "406" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Babies are born with around 300; many fuse together as they grow.",
  },
  {
    id: "en_sci_16",
    category: "🚀 SCIENCE",
    text: "Which gas do plants take in during photosynthesis?",
    options: { A: "Oxygen", B: "Nitrogen", C: "Carbon dioxide", D: "Hydrogen" },
    correctOption: "C",
    difficulty: 1,
    funFact: "They release oxygen in return — the reverse of our breathing.",
  },
  {
    id: "en_sci_17",
    category: "🚀 SCIENCE",
    text: "What does 'open source' mean for software?",
    options: { A: "Free but secret", B: "The source code is publicly viewable", C: "Browser-only", D: "Works offline" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Linux is the best-known open-source project and runs most of the world's servers.",
  },
  {
    id: "en_night_10",
    category: "🍸 NIGHTLIFE",
    text: "What is ayran?",
    options: { A: "A yoghurt drink", B: "A fruit juice", C: "A herbal tea", D: "A pastry" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Yoghurt, water and salt — the default drink with a meal in Turkey.",
  },
  {
    id: "en_night_11",
    category: "🍸 NIGHTLIFE",
    text: "Which fruit gives classic lemonade its name?",
    options: { A: "Lemon", B: "Pineapple", C: "Banana", D: "Cherry" },
    correctOption: "A",
    difficulty: 1,
    funFact: "The word traces back to the Persian 'limun'.",
  },
];

export interface QuizSelectionOptions {
  /** Kurulum modalinde secilen konular; bos/atlanirsa hepsi. */
  topics?: readonly string[];
  /** Yakinda sorulmus soru kimlikleri (bkz. questionHistory) — en yeni once. */
  recentIds?: readonly string[];
}

function shuffle<T>(arr: readonly T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function poolFor(locale: string): QuizQuestion[] {
  if (locale.startsWith("de")) return deQuestions;
  if (locale.startsWith("en")) return enQuestions;
  return trQuestions;
}

/**
 * Bir tur icin soru secer.
 *
 * Iki davranis onceki surumden farkli:
 *
 * 1. KONU FILTRESI. Kurulum modali host'a kategori sectiriyordu ama secim
 *    hicbir yere gitmiyordu — getQuizQuestions kategori parametresi bile
 *    almiyordu. Artik gecirilen konular uygulaniyor; secimle eslesen soru
 *    yoksa filtre yok sayiliyor (host'a bos tur gostermektense tum havuzdan
 *    sormak yeg).
 *
 * 2. TEKRAR HAFIZASI. Onceden her oturum havuzu sifirdan karistiriyordu,
 *    yani haftalik gelen mudavim ayni sorulari goruyordu. Once HIC
 *    sorulmamis sorular geliyor; havuz yetmezse en UZUN SURE once sorulanlar
 *    ekleniyor. Havuz tur uzunlugundan kucukse tekrar kacinilmaz, o durumda
 *    da ust uste ayni soru gelmiyor.
 */
export function getQuizQuestions(
  locale: string = "tr",
  count: number = 5,
  options: QuizSelectionOptions = {},
): QuizQuestion[] {
  const basePool = poolFor(locale);

  const wanted = options.topics && options.topics.length > 0 ? new Set(options.topics) : null;
  const filtered = wanted ? basePool.filter((q) => {
    const topic = topicOf(q);
    return topic !== null && wanted.has(topic);
  }) : basePool;
  const pool = filtered.length > 0 ? filtered : basePool;

  // recentIds en yeniden eskiye; indeks kucukse "daha yakinda soruldu".
  const recency = new Map<string, number>();
  (options.recentIds ?? []).forEach((id, i) => {
    if (!recency.has(id)) recency.set(id, i);
  });

  const unseen = shuffle(pool.filter((q) => !recency.has(q.id)));
  const seen = pool
    .filter((q) => recency.has(q.id))
    .sort((a, b) => recency.get(b.id)! - recency.get(a.id)!); // en eski once

  const ordered = [...unseen, ...seen];
  if (ordered.length >= count) return ordered.slice(0, count);

  // Havuz turdan kisa: bastan devam et, ama ust uste ayni soruyu verme.
  const result = [...ordered];
  while (result.length < count) {
    const lap = shuffle(ordered);
    if (lap[0]?.id === result[result.length - 1]?.id && lap.length > 1) {
      [lap[0], lap[1]] = [lap[1], lap[0]];
    }
    result.push(...lap.slice(0, count - result.length));
  }
  return result;
}
