import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={`${inter.className} bg-hc-bg text-hc-text text-base md:text-lg min-h-screen flex flex-col`}>
        <div className="bg-hc-accent text-hc-bg p-3 text-center font-bold text-lg md:text-xl" role="alert">
          Bu bir tıbbi tavsiye değildir, yalnızca dil sadeleştirme aracıdır. Lütfen doktorunuza danışın.
        </div>
        <main className="flex-grow p-4 md:p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
