import type { QuizQuestion } from "../../types/database";

// HENGAME quiz havuzu — TR. Secim ve filtreleme mantigi
// src/lib/quizQuestions.ts icinde; burasi sadece veri.

export const trQuestions: QuizQuestion[] = [
  // ─── GECE HAYATI & KAFE KÜLTÜRÜ ───
  {
    id: "tr_night_1",
    category: "🍸 GECE & KAFE",
    text: "Geleneksel bir 'Virgin Mojito'ya karakterini veren bitki hangisidir?",
    options: { A: "Fesleğen", B: "Nane", C: "Kekik", D: "Biberiye" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Nane yapraklarını ezmek değil, hafifçe bastırmak gerekir; ezilince acı tat veriyor.",
  },
  {
    id: "tr_night_2",
    category: "🍸 GECE & KAFE",
    text: "Kahve çekirdeği aslında botanik olarak nedir?",
    options: { A: "Ağaç Kabuğu", B: "Bir Meyvenin Çekirdeği", C: "Kök Yumrusu", D: "Yaprak Tomurcuğu" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Kahve çekirdekleri, 'kahve kirazı' adı verilen kırmızı meyvelerin içindeki tohumlardır.",
  },
  {
    id: "tr_night_3",
    category: "🍸 GECE & KAFE",
    text: "Bir espressonun üzerindeki altın rengi köpüğe ne ad verilir?",
    options: { A: "Krema", B: "Crema", C: "Köpük", D: "Foam" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Crema, taze çekirdekteki karbondioksitin basınç altında yağlarla birleşmesiyle oluşuyor; eskimiş kahvede neredeyse hiç çıkmıyor.",
  },

  // ─── MÜZİK & POPÜLER KÜLTÜR ───
  {
    id: "tr_music_1",
    category: "🎵 MÜZİK",
    text: "Spotify'da tüm zamanların ilk 3 milyar dinlenmeyi aşan şarkısı hangisidir?",
    options: { A: "Blinding Lights (The Weeknd)", B: "Shape of You (Ed Sheeran)", C: "Despacito (Luis Fonsi)", D: "Dance Monkey (Tones and I)" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ed Sheeran'ın 'Shape of You' şarkısı 2021'de 3 milyar barajını ilk geçen şarkı olmuştur.",
  },
  {
    id: "tr_music_2",
    category: "🎵 MÜZİK",
    text: "Efsanevi rock grubu Queen'in 'Bohemian Rhapsody' şarkısı hangi yılda yayınlanmıştır?",
    options: { A: "1969", B: "1975", C: "1982", D: "1989" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Plak şirketi şarkının 6 dakikalık süresini radyolar için çok uzun bulup ilk başta reddetmişti!",
  },
  {
    id: "tr_music_3",
    category: "🎵 MÜZİK",
    text: "Daft Punk'ın ikonik robot kaskları ilk olarak hangi albüm döneminde sahneye çıktı?",
    options: { A: "Homework", B: "Discovery", C: "Human After All", D: "Random Access Memories" },
    correctOption: "B",
    difficulty: 3,
    funFact: "İkili, 1999 yılında bir stüdyo patlamasında robota dönüştüklerini iddia eden eğlenceli bir hikaye uydurmuştu.",
  },

  // ─── SİNEMA & DİZİ ───
  {
    id: "tr_cinema_1",
    category: "🎬 SİNEMA",
    text: "'Matrix' filminde Neo'nun gerçeği görmek için seçtiği hap hangi renktir?",
    options: { A: "Mavi", B: "Kırmızı", C: "Yeşil", D: "Sarı" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Mavi hap illüzyon dolu Matrix'te uyumayı, Kırmızı hap ise acımasız gerçek dünyayı temsil eder.",
  },
  {
    id: "tr_cinema_2",
    category: "🎬 SİNEMA",
    text: "Quentin Tarantino'nun 'Pulp Fiction' filmindeki meşhur parlayan çantanın içinde ne olduğu filmde açıklanır mı?",
    options: { A: "Elmaslar", B: "Marcellus'un Ruhu", C: "Altın Külçeleri", D: "Hiçbir zaman açıklanmaz" },
    correctOption: "D",
    difficulty: 2,
    funFact: "Tarantino, çantanın içinde ne olduğunu izleyicinin hayal gücüne bırakmak için bilerek gizli tutmuştur.",
  },
  {
    id: "tr_cinema_3",
    category: "🎬 SİNEMA",
    text: "Yüzüklerin Efendisi serisinde 'Tek Yüzük' hangi dağın ateşinde dövülmüştür?",
    options: { A: "Hüküm Dağı (Mount Doom)", B: "Erebor Dağı", C: "Sisli Dağlar", D: "Caradhras" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Yüzük yalnızca dövüldüğü yer olan Hüküm Dağı'nın lavlarında yok edilebilir.",
  },

  // ─── ZEKA & MANTIK TUZAKLARI ───
  {
    id: "tr_brain_1",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bir yarışta ikinci sıradaki koşucuyu geçerseniz kaçıncı olursunuz?",
    options: { A: "Birinci", B: "İkinci", C: "Üçüncü", D: "Yarışı kazanırsınız" },
    correctOption: "B",
    difficulty: 1,
    funFact: "İkincinin yerini aldığınız için siz ikinci olursunuz, birinci hâlâ önünüzdedir!",
  },
  {
    id: "tr_brain_2",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bazı aylar 30, bazıları 31 çeker. Kaç ayda 28 gün vardır?",
    options: { A: "1 (Şubat)", B: "6", C: "12 (Hepsinde)", D: "Hiçbiri" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Yılın 12 ayının tamamında en az 28 gün bulunmaktadır!",
  },
  {
    id: "tr_brain_3",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bir tuğlanın ağırlığı 1 kg artı yarım tuğla kadardır. Bir tuğla kaç kg'dır?",
    options: { A: "1.5 kg", B: "2 kg", C: "2.5 kg", D: "3 kg" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Matematiksel olarak: X = 1 + X/2 denkleminden X = 2 kg çıkar.",
  },

  // ─── GENEL KÜLTÜR & COĞRAFYA ───
  {
    id: "tr_gen_1",
    category: "🌍 GENEL KÜLTÜR",
    text: "Dünyanın yüzölçümü bakımından en büyük okyanusu hangisidir?",
    options: { A: "Atlantik (Atlas)", B: "Pasifik (Büyük Okyanus)", C: "Hint Okyanusu", D: "Arktik Okyanusu" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Pasifik Okyanusu, dünyadaki tüm kara parçalarının toplamından daha geniş bir alanı kaplar!",
  },
  {
    id: "tr_gen_2",
    category: "🌍 GENEL KÜLTÜR",
    text: "Hangi element periyodik tabloda 'Au' simgesi ile gösterilir?",
    options: { A: "Gümüş", B: "Altın", C: "Alüminyum", D: "Bakır" },
    correctOption: "B",
    difficulty: 1,
    funFact: "'Au' simgesi, Latince 'parlayan şafak' anlamına gelen 'Aurum' kelimesinden gelir.",
  },
  {
    id: "tr_gen_3",
    category: "🌍 GENEL KÜLTÜR",
    text: "Mona Lisa tablosu günümüzde hangi müzede sergilenmektedir?",
    options: { A: "British Museum", B: "Prado Müzesi", C: "Louvre Müzesi", D: "Uffizi Galerisi" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Mona Lisa tablosunun kendi posta kutusu vardır ve her yıl binlerce aşk mektubu alır!",
  },
  {
    id: "tr_gen_4",
    category: "🌍 GENEL KÜLTÜR",
    text: "Nobel Edebiyat Ödülü'nü kazanan ilk Türk yazar kimdir?",
    options: { A: "Yaşar Kemal", B: "Orhan Pamuk", C: "Sabahattin Ali", D: "Nazım Hikmet" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Orhan Pamuk, Nobel Edebiyat Ödülü'nü 2006 yılında kazanmıştır.",
  },
  {
    id: "tr_gen_5",
    category: "🌍 GENEL KÜLTÜR",
    text: "Japonya'nın resmi para birimi nedir?",
    options: { A: "Yen", B: "Yuan", C: "Won", D: "Baht" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Japonca 'Yen', kelime anlamı olarak 'yuvarlak nesne' veya 'daire' demektir.",
  },

  // ─── BİLİM & TEKNOLOJİ ───
  {
    id: "tr_sci_1",
    category: "🚀 BİLİM & TEKNO",
    text: "Güneş Sistemi'ndeki en sıcak gezegen hangisidir?",
    options: { A: "Merkür", B: "Venüs", C: "Mars", D: "Jüpiter" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Güneş'e en yakın gezegen Merkür olsa da, yoğun sera gazı atmosferi nedeniyle en sıcağı Venüs'tür (465°C)!",
  },
  {
    id: "tr_sci_2",
    category: "🚀 BİLİM & TEKNO",
    text: "Tarihteki ilk bilgisayar programcısı olarak kabul edilen bilim insanı kimdir?",
    options: { A: "Alan Turing", B: "Ada Lovelace", C: "Nikola Tesla", D: "Charles Babbage" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Ada Lovelace, 1843 yılında mekanik bilgisayar için ilk algoritmayı yazmıştır.",
  },
  {
    id: "tr_sci_3",
    category: "🚀 BİLİM & TEKNO",
    text: "Işığın boşluktaki hızı saniyede yaklaşık kaç kilometredir?",
    options: { A: "150.000 km/s", B: "300.000 km/s", C: "500.000 km/s", D: "1.000.000 km/s" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Işık hızında seyahat edebilseydiniz, 1 saniyede Dünya'nın etrafını 7.5 kez turlayabilirdiniz!",
  },
  {
    id: "tr_sci_4",
    category: "🚀 BİLİM & TEKNO",
    text: "İnsan vücudundaki en güçlü ve en büyük kemik hangisidir?",
    options: { A: "Uyluk Kemiği (Femur)", B: "Kaval Kemiği", C: "Omurga", D: "Kafatası" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Femur kemiği betondan daha yüksek basınca ve vücut ağırlığının 30 katına kadar yüke dayanabilir.",
  },
  {
    id: "tr_sci_5",
    category: "🚀 BİLİM & TEKNO",
    text: "Ahtapotların kaç adet kalbi vardır?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Ahtapotların 3 kalbi ve mavi renkte kanı vardır!",
  },
  {
    id: "tr_cafe_10",
    category: "☕ KAHVE & KAFE",
    text: "Kahve bitkisinin anavatanı neresidir?",
    options: { A: "Brezilya", B: "Etiyopya", C: "Kolombiya", D: "Yemen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Efsaneye göre keçi çobanı Kaldi, keçilerinin kahve kirazı yedikten sonraki hâlini fark edip durumu keşfetmiş.",
  },
  {
    id: "tr_cafe_11",
    category: "☕ KAHVE & KAFE",
    text: "'Cappuccino' kelimesi kelime anlamıyla ne demek?",
    options: { A: "Küçük kukuleta", B: "Süt köpüğü", C: "Çift kahve", D: "Sabah içeceği" },
    correctOption: "A",
    difficulty: 2,
    funFact: "İsim, Kapuçin rahiplerinin cüppe renginden geliyor.",
  },
  {
    id: "tr_cafe_12",
    category: "☕ KAHVE & KAFE",
    text: "Türk kahvesi geleneksel olarak neyle pişirilir?",
    options: { A: "Filtre makinesi", B: "Cezve", C: "French press", D: "Su ısıtıcısı" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Telve fincanda kalır ve geleneksel olarak fal bakmakta kullanılır.",
  },
  {
    id: "tr_cafe_13",
    category: "☕ KAHVE & KAFE",
    text: "Matcha neyden yapılır?",
    options: { A: "Kavrulmuş pirinç", B: "Toz hâline getirilmiş yeşil çay yaprağı", C: "Kurutulmuş nane", D: "Fermente kakao" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Matcha'da yaprağın tamamı içildiği için kafein oranı demlenmiş yeşil çaydan yüksek.",
  },
  {
    id: "tr_cafe_14",
    category: "☕ KAHVE & KAFE",
    text: "'Cold brew' nedir?",
    options: { A: "Sıcak demlenip soğutulan kahve", B: "Soğuk suyla uzun sürede demlenen kahve", C: "Dondurulmuş espresso", D: "Dondurmalı kahve" },
    correctOption: "B",
    difficulty: 2,
    funFact: "12-24 saat süren demleme daha yumuşak ve daha az asidik bir tat veriyor.",
  },
  {
    id: "tr_cafe_15",
    category: "☕ KAHVE & KAFE",
    text: "Dünya kahve üretimine hangi iki tür hâkimdir?",
    options: { A: "Arabica ve Robusta", B: "Mocha ve Latte", C: "Java ve Sumatra", D: "Bourbon ve Typica" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Robusta, Arabica'nın yaklaşık iki katı kafein içeriyor.",
  },
  {
    id: "tr_cafe_16",
    category: "☕ KAHVE & KAFE",
    text: "Latte art nedir?",
    options: { A: "Çekirdek dizilimi", B: "Süt köpüğüyle yapılan desen", C: "Boyalı fincan", D: "Bir kavurma yöntemi" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Kalp ve rozeta, latte art'ın iki temel figürü sayılıyor.",
  },
  {
    id: "tr_cafe_17",
    category: "☕ KAHVE & KAFE",
    text: "Hangi şehrin kahvehane kültürü UNESCO listesinde?",
    options: { A: "Paris", B: "Viyana", C: "Lizbon", D: "Prag" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Viyana kahvehane kültürü 2011'den beri somut olmayan kültürel miras listesinde.",
  },
  {
    id: "tr_cafe_18",
    category: "☕ KAHVE & KAFE",
    text: "En çok fermente edilen çay türü hangisidir?",
    options: { A: "Yeşil çay", B: "Beyaz çay", C: "Siyah çay", D: "Bitki çayı" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Çin'de siyah çaya, demin rengi yüzünden 'kırmızı çay' deniyor.",
  },
  {
    id: "tr_cafe_19",
    category: "☕ KAHVE & KAFE",
    text: "Süt neden protein içeriği sayesinde iyi köpürür?",
    options: { A: "Proteinler hava kabarcıklarını sabitler", B: "Yağ oranı düşüktür", C: "Şeker içerir", D: "Soğuk olduğu için" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Bitkisel içecekler bu yüzden çoğu zaman köpürmeyi destekleyen katkılar içeriyor.",
  },
  {
    id: "tr_music_10",
    category: "🎵 MÜZİK",
    text: "'The Dark Side of the Moon' albümü hangi gruba ait?",
    options: { A: "Led Zeppelin", B: "Pink Floyd", C: "The Doors", D: "Queen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Albüm ABD listelerinde 900 haftadan fazla kaldı.",
  },
  {
    id: "tr_music_11",
    category: "🎵 MÜZİK",
    text: "Klasik gitarda kaç tel vardır?",
    options: { A: "Dört", B: "Beş", C: "Altı", D: "Yedi" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Bas gitarda klasik olarak dört tel bulunur; karışıklık çoğu zaman buradan çıkıyor.",
  },
  {
    id: "tr_music_12",
    category: "🎵 MÜZİK",
    text: "Reggae müziği hangi ülkede doğmuştur?",
    options: { A: "Küba", B: "Jamaika", C: "Brezilya", D: "Trinidad" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Bob Marley'nin 'Exodus' albümü Time dergisi tarafından yüzyılın albümü seçildi.",
  },
  {
    id: "tr_music_13",
    category: "🎵 MÜZİK",
    text: "Standart bir piyanoda kaç tuş vardır?",
    options: { A: "76", B: "81", C: "88", D: "92" },
    correctOption: "C",
    difficulty: 2,
    funFact: "52 beyaz ve 36 siyah tuş toplamda tam 88 ediyor.",
  },
  {
    id: "tr_music_14",
    category: "🎵 MÜZİK",
    text: "Techno müziğin doğduğu şehir hangisidir?",
    options: { A: "Berlin", B: "Detroit", C: "Manchester", D: "Şikago" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Berlin sonradan Avrupa'nın techno başkenti oldu ama tür Detroit'te çıktı.",
  },
  {
    id: "tr_music_15",
    category: "🎵 MÜZİK",
    text: "Müzikte 'BPM' neyi ifade eder?",
    options: { A: "Ses yüksekliği", B: "Nota sayısı", C: "Dakikadaki vuruş", D: "Kanal sayısı" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Klasik house genelde 120-130 BPM aralığında.",
  },
  {
    id: "tr_music_16",
    category: "🎵 MÜZİK",
    text: "Hip-hop hangi bölgede ortaya çıktı?",
    options: { A: "Bronx", B: "Brooklyn", C: "Harlem", D: "Queens" },
    correctOption: "A",
    difficulty: 2,
    funFact: "DJ Kool Herc'in mahalle partileri hip-hop'ın başlangıcı sayılıyor.",
  },
  {
    id: "tr_music_17",
    category: "🎵 MÜZİK",
    text: "'A cappella' ne demektir?",
    options: { A: "Sadece piyanoyla", B: "Enstrümansız", C: "Sadece enstrümantal", D: "Orkestrayla" },
    correctOption: "B",
    difficulty: 1,
    funFact: "İtalyanca 'şapel usulü' anlamına geliyor.",
  },
  {
    id: "tr_cinema_10",
    category: "🎬 SİNEMA",
    text: "'Inception' filminin yönetmeni kimdir?",
    options: { A: "Ridley Scott", B: "Christopher Nolan", C: "Denis Villeneuve", D: "David Fincher" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Dönen koridor sahnesi bilgisayarla değil, gerçekten dönen bir sette çekildi.",
  },
  {
    id: "tr_cinema_11",
    category: "🎬 SİNEMA",
    text: "'Forrest Gump' filminde başrol kimdir?",
    options: { A: "Tom Hanks", B: "Tom Cruise", C: "Kevin Costner", D: "Robin Williams" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Tom Hanks üst üste iki yıl En İyi Erkek Oyuncu Oscar'ını kazandı.",
  },
  {
    id: "tr_cinema_12",
    category: "🎬 SİNEMA",
    text: "Sinemada 'cameo' ne demektir?",
    options: { A: "Senaryo hatası", B: "Çok kısa bir görünme", C: "Kamera hareketi", D: "Jenerik" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Alfred Hitchcock neredeyse bütün filmlerinde kısa bir görünme yapardı.",
  },
  {
    id: "tr_cinema_13",
    category: "🎬 SİNEMA",
    text: "'Game of Thrones' dizisi hangi kurgusal kıtada geçer?",
    options: { A: "Narnia", B: "Westeros", C: "Orta Dünya", D: "Panem" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Çekimler Kuzey İrlanda, Hırvatistan ve İzlanda'da yapıldı.",
  },
  {
    id: "tr_cinema_14",
    category: "🎬 SİNEMA",
    text: "'CGI' kısaltması neyi ifade eder?",
    options: { A: "Bilgisayarla üretilen görüntü", B: "Klasik film tekniği", C: "Kamera yönetimi", D: "Renk düzenleme" },
    correctOption: "A",
    difficulty: 2,
    funFact: "1982 yapımı 'Tron', yoğun CGI kullanan ilk filmlerden sayılıyor.",
  },
  {
    id: "tr_cinema_15",
    category: "🎬 SİNEMA",
    text: "Dünya çapında 2 milyar doları ilk aşan film hangisidir?",
    options: { A: "Titanic", B: "Avatar", C: "Avengers: Endgame", D: "Star Wars" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Titanic' bu eşiği 1998'de geçti; rekoru on bir yıl sonra 'Avatar' kırdı.",
  },
  {
    id: "tr_brain_10",
    category: "🧠 ZEKA TUZAĞI",
    text: "Bir çiftçinin 17 koyunu var. Dokuzu hariç hepsi kaçıyor. Kaç koyun kalır?",
    options: { A: "8", B: "9", C: "17", D: "0" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Dokuzu hariç hepsi' ifadesi tam olarak dokuzunun kaldığı anlamına geliyor.",
  },
  {
    id: "tr_brain_11",
    category: "🧠 ZEKA TUZAĞI",
    text: "Kaç ay 28 gün çeker?",
    options: { A: "Bir", B: "İki", C: "On iki", D: "Hiçbiri" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Her ay en az 28 gün çeker; soruda 'tam olarak' denmiyor.",
  },
  {
    id: "tr_brain_12",
    category: "🧠 ZEKA TUZAĞI",
    text: "Kuruttukça ıslanan şey nedir?",
    options: { A: "Güneş", B: "Havlu", C: "Kâğıt", D: "Sünger" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Havlu başka şeyleri kuruturken kendisi suyu emiyor.",
  },
  {
    id: "tr_brain_13",
    category: "🧠 ZEKA TUZAĞI",
    text: "Üç kedi üç dakikada üç fare yakalıyorsa, 100 kedi 100 fareyi kaç dakikada yakalar?",
    options: { A: "Üç dakika", B: "100 dakika", C: "33 dakika", D: "Bir dakika" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Her kedi bir fareyi üç dakikada yakalıyor; sayıyı artırmak süreyi değiştirmiyor.",
  },
  {
    id: "tr_brain_14",
    category: "🧠 ZEKA TUZAĞI",
    text: "Boynu olup başı olmayan nedir?",
    options: { A: "Anahtar", B: "Şişe", C: "Ayakkabı", D: "Sandalye" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Gitar ve kemanın da boynu vardır ama başı yoktur.",
  },
  {
    id: "tr_brain_15",
    category: "🧠 ZEKA TUZAĞI",
    text: "100'den 10'u kaç kez çıkarabilirsiniz?",
    options: { A: "On kez", B: "Bir kez", C: "Dokuz kez", D: "Sonsuz" },
    correctOption: "B",
    difficulty: 2,
    funFact: "İlk çıkarmadan sonra sayı artık 100 değil, 90.",
  },
  {
    id: "tr_brain_16",
    category: "🧠 ZEKA TUZAĞI",
    text: "İki baba ve iki oğul balığa gidiyor, herkes bir balık tutuyor ama toplam üç balık var. Nasıl?",
    options: { A: "Biri hile yapıyor", B: "Dede, baba, oğul", C: "Bir balık kaçtı", D: "Birini paylaştılar" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ortadaki kişi hem baba hem oğul; üç kişi, dört rol.",
  },
  {
    id: "tr_gen_10",
    category: "🌍 GENEL KÜLTÜR",
    text: "Dünyanın en uzun kıyı şeridine sahip ülkesi hangisidir?",
    options: { A: "Rusya", B: "Kanada", C: "Avustralya", D: "Endonezya" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Kanada'nın kıyı şeridi 200.000 kilometreyi aşıyor; sebebi sayısız Arktik adası.",
  },
  {
    id: "tr_gen_11",
    category: "🌍 GENEL KÜLTÜR",
    text: "Avustralya'nın başkenti neresidir?",
    options: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Brisbane" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Canberra, Sidney ile Melbourne anlaşamayınca uzlaşma olarak inşa edildi.",
  },
  {
    id: "tr_gen_12",
    category: "🌍 GENEL KÜLTÜR",
    text: "Berlin Duvarı hangi yıl yıkıldı?",
    options: { A: "1987", B: "1989", C: "1990", D: "1991" },
    correctOption: "B",
    difficulty: 1,
    funFact: "9 Kasım 1989'daki sınır açılımı, yanlış anlaşılan bir basın toplantısının sonucuydu.",
  },
  {
    id: "tr_gen_13",
    category: "🌍 GENEL KÜLTÜR",
    text: "Ana dili en çok konuşulan dil hangisidir?",
    options: { A: "İngilizce", B: "İspanyolca", C: "Mandarin", D: "Hintçe" },
    correctOption: "C",
    difficulty: 2,
    funFact: "İngilizce ancak ikinci dil konuşanlar sayılınca başa geçiyor.",
  },
  {
    id: "tr_gen_14",
    category: "🌍 GENEL KÜLTÜR",
    text: "Dünyanın en büyük iç denizi hangisidir?",
    options: { A: "Karadeniz", B: "Hazar Denizi", C: "Baltık Denizi", D: "Ölü Deniz" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Hazar o kadar büyük ki göl mü deniz mi olduğu hâlâ tartışılıyor.",
  },
  {
    id: "tr_gen_15",
    category: "🌍 GENEL KÜLTÜR",
    text: "Karada en hızlı hayvan hangisidir?",
    options: { A: "Çita", B: "Antilop", C: "Aslan", D: "Deve kuşu" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Çita saatte 110 kilometreye ulaşıyor ama bu hızı yalnızca birkaç saniye koruyabiliyor.",
  },
  {
    id: "tr_gen_16",
    category: "🌍 GENEL KÜLTÜR",
    text: "En çok saat dilimine sahip ülke hangisidir?",
    options: { A: "Rusya", B: "ABD", C: "Çin", D: "Fransa" },
    correctOption: "D",
    difficulty: 3,
    funFact: "Denizaşırı toprakları sayesinde Fransa on iki saat dilimine yayılıyor.",
  },
  {
    id: "tr_gen_17",
    category: "🌍 GENEL KÜLTÜR",
    text: "Bir futbol maçında sahada takım başına kaç oyuncu bulunur?",
    options: { A: "Dokuz", B: "On", C: "On bir", D: "On iki" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Kaleci, kendi ceza sahasında topa elle dokunabilen tek oyuncudur.",
  },
  {
    id: "tr_sci_10",
    category: "🚀 BİLİM & TEKNO",
    text: "'Fe' hangi elementin simgesidir?",
    options: { A: "Flor", B: "Demir", C: "Kurşun", D: "Gümüş" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Fe', Latince 'ferrum' kelimesinden geliyor.",
  },
  {
    id: "tr_sci_11",
    category: "🚀 BİLİM & TEKNO",
    text: "Güneş ışığı Dünya'ya ne kadar sürede ulaşır?",
    options: { A: "8 saniye", B: "8 dakika", C: "8 saat", D: "8 gün" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Güneş'i her zaman sekiz dakika önceki hâliyle görüyoruz.",
  },
  {
    id: "tr_sci_12",
    category: "🚀 BİLİM & TEKNO",
    text: "İnsülin hangi organda üretilir?",
    options: { A: "Karaciğer", B: "Böbrek", C: "Pankreas", D: "Dalak" },
    correctOption: "C",
    difficulty: 2,
    funFact: "İnsülin 1921'de izole edildi ve diyabet tedavisini kökten değiştirdi.",
  },
  {
    id: "tr_sci_13",
    category: "🚀 BİLİM & TEKNO",
    text: "Bir byte kaç bitten oluşur?",
    options: { A: "Sekiz", B: "On", C: "Bir", D: "Bin" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Bir kilobyte teknik olarak 1024 byte; disk kapasitelerinin etikete uymamasının sebebi bu.",
  },
  {
    id: "tr_sci_14",
    category: "🚀 BİLİM & TEKNO",
    text: "Yetişkin bir insanda yaklaşık kaç kemik vardır?",
    options: { A: "106", B: "206", C: "306", D: "406" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Bebekler yaklaşık 300 kemikle doğuyor; büyürken birçoğu kaynaşıyor.",
  },
  {
    id: "tr_sci_15",
    category: "🚀 BİLİM & TEKNO",
    text: "Bitkiler fotosentezde hangi gazı alır?",
    options: { A: "Oksijen", B: "Azot", C: "Karbondioksit", D: "Hidrojen" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Karşılığında oksijen veriyorlar; bizim solunumumuzun tam tersi.",
  },
  {
    id: "tr_sci_16",
    category: "🚀 BİLİM & TEKNO",
    text: "Yazılımda 'açık kaynak' ne demektir?",
    options: { A: "Ücretsiz ama gizli", B: "Kaynak kodu herkese açık", C: "Sadece tarayıcıda çalışır", D: "İnternetsiz çalışır" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Linux en bilinen açık kaynak projesi ve dünyadaki sunucuların çoğunda çalışıyor.",
  },
  {
    id: "tr_sci_17",
    category: "🚀 BİLİM & TEKNO",
    text: "Güneş'e en yakın gezegen hangisidir?",
    options: { A: "Venüs", B: "Merkür", C: "Mars", D: "Dünya" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Buna rağmen en sıcak gezegen Venüs; sebebi yoğun atmosferi.",
  },
  {
    id: "tr_night_10",
    category: "🍸 GECE & KAFE",
    text: "'Mocktail' nedir?",
    options: { A: "Alkolsüz kokteyl", B: "Çift kokteyl", C: "Sıcak kokteyl", D: "Kahveli kokteyl" },
    correctOption: "A",
    difficulty: 1,
    funFact: "İsim, İngilizce 'mock' (taklit) ve 'cocktail' kelimelerinin birleşimi.",
  },
  {
    id: "tr_night_11",
    category: "🍸 GECE & KAFE",
    text: "Ayran neyden yapılır?",
    options: { A: "Yoğurt, su ve tuz", B: "Süt ve şeker", C: "Kefir ve bal", D: "Peynir suyu" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Ayran, Türkiye'de yemeğin yanında en çok tercih edilen içecek.",
  },
];
