import type { QuizQuestion } from "../../types/database";

// HENGAME quiz havuzu — DE. Secim ve filtreleme mantigi
// src/lib/quizQuestions.ts icinde; burasi sadece veri.

export const deQuestions: QuizQuestion[] = [
  // ─── NIGHTLIFE & CAFE ───
  {
    id: "de_night_1",
    category: "🍸 NACHTLEBEN",
    text: "Welches Kraut gibt einem Virgin Mojito seinen Charakter?",
    options: { A: "Basilikum", B: "Minze", C: "Thymian", D: "Rosmarin" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Minzblätter werden nur angedrückt, nicht zerstoßen – sonst werden sie bitter.",
  },
  {
    id: "de_night_2",
    category: "🍸 NACHTLEBEN",
    text: "Wie heißt die goldene Schaumschicht auf einem Espresso?",
    options: { A: "Sahne", B: "Crema", C: "Haube", D: "Schaumkrone" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Crema entsteht, wenn unter Druck gelöstes Kohlendioxid aus frischen Bohnen mit den Kaffeeölen aufschäumt – bei altem Kaffee bleibt sie fast aus.",
  },
  {
    id: "de_night_3",
    category: "🍸 NACHTLEBEN",
    text: "Was ist eine Kaffeebohne aus botanischer Sicht?",
    options: { A: "Baumrinde", B: "Samen einer Steinfrucht", C: "Wurzelknolle", D: "Blattknospe" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Kaffeebohnen sind eigentlich die Samen der roten Kaffeekirsche!",
  },

  // ─── MUSIK & POPKULTUR ───
  {
    id: "de_music_1",
    category: "🎵 MUSIK",
    text: "Welcher Song hat auf Spotify als erster aller Zeiten 3 Milliarden Streams erreicht?",
    options: { A: "Blinding Lights (The Weeknd)", B: "Shape of You (Ed Sheeran)", C: "Despacito (Luis Fonsi)", D: "Dance Monkey" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ed Sheerans Megahit knackte im Dezember 2021 als erster Track die 3-Milliarden-Marke.",
  },
  {
    id: "de_music_2",
    category: "🎵 MUSIK",
    text: "In welchem Jahr erschien der legendäre Queen-Hit 'Bohemian Rhapsody'?",
    options: { A: "1969", B: "1975", C: "1982", D: "1989" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Plattenfirma hielt den Song mit fast 6 Minuten anfangs für viel zu lang fürs Radio!",
  },

  // ─── KINO & SERIEN ───
  {
    id: "de_cinema_1",
    category: "🎬 KINO",
    text: "Welche Pille wählt Neo in 'Matrix', um die Wahrheit über die Welt zu erfahren?",
    options: { A: "Blau", B: "Rot", C: "Grün", D: "Gelb" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die rote Pille öffnet das Tor zur Realität, die blaue lässt einen in der Matrix weiterschlafen.",
  },
  {
    id: "de_cinema_2",
    category: "🎬 KINO",
    text: "Wo wurde der Eine Ring in 'Der Herr der Ringe' geschmiedet?",
    options: { A: "Schicksalsberg (Mount Doom)", B: "Erebor", C: "Nebelgebirge", D: "Isengart" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Der Ring kann nur dort zerstört werden, wo Sauron ihn einst geschmiedet hat.",
  },

  // ─── LOGIK & DENKSPORT ───
  {
    id: "de_brain_1",
    category: "🧠 DENKSPORT",
    text: "Wenn du in einem Rennen den Zweiten überholst, an welcher Position bist du dann?",
    options: { A: "Erster", B: "Zweiter", C: "Dritter", D: "Sieger" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Du übernimmst den Platz des Zweiten, der Erste ist immer noch vor dir!",
  },
  {
    id: "de_brain_2",
    category: "🧠 DENKSPORT",
    text: "Manche Monate haben 30 Tage, manche 31. Wie viele Monate haben 28 Tage?",
    options: { A: "1 (Februar)", B: "6", C: "Alle 12", D: "Keiner" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Jeder der 12 Monate hat mindestens 28 Tage!",
  },

  // ─── ALLGEMEINWISSEN ───
  {
    id: "de_gen_1",
    category: "🌍 WISSEN",
    text: "Was ist die Hauptstadt von Deutschland?",
    options: { A: "München", B: "Berlin", C: "Hamburg", D: "Frankfurt" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Berlin hat mehr Brücken als Venedig – insgesamt rund 960 Stück!",
  },
  {
    id: "de_gen_2",
    category: "🌍 WISSEN",
    text: "Welches chemische Element hat das Symbol 'Au' im Periodensystem?",
    options: { A: "Silber", B: "Gold", C: "Aluminium", D: "Kupfer" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Das Symbol leitet sich vom lateinischen Wort 'Aurum' (Morgenröte) ab.",
  },
  {
    id: "de_gen_3",
    category: "🌍 WISSEN",
    text: "In welchem Museum hängt das berühmte Gemälde 'Mona Lisa'?",
    options: { A: "British Museum", B: "Prado", C: "Louvre", D: "Uffizien" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Die Mona Lisa hat im Louvre einen eigenen Briefkasten für Liebesbriefe!",
  },
  {
    id: "de_gen_4",
    category: "🌍 WISSEN",
    text: "In welchem Jahr fiel die Berliner Mauer?",
    options: { A: "1989", B: "1990", C: "1991", D: "1988" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Der historische Mauerfall ereignete sich am Abend des 9. November 1989.",
  },

  // ─── WISSENSCHAFT & TECH ───
  {
    id: "de_sci_1",
    category: "🚀 WISSENSCHAFT",
    text: "Welcher Planet ist der heißeste in unserem Sonnensystem?",
    options: { A: "Merkur", B: "Venus", C: "Mars", D: "Jupiter" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Wegen des extremen Treibhauseffekts herrschen auf der Venus ca. 465°C!",
  },
  {
    id: "de_sci_2",
    category: "🚀 WISSENSCHAFT",
    text: "Wie viele Herzen hat ein Oktopus (Krake)?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Kraken haben 3 Herzen und ihr Blut ist durch Kupfer blau gefärbt!",
  },
  {
    id: "de_sci_3",
    category: "🚀 WISSENSCHAFT",
    text: "Wer gilt als die erste Computerprogrammiererin der Geschichte?",
    options: { A: "Alan Turing", B: "Ada Lovelace", C: "Marie Curie", D: "Grace Hopper" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Ada Lovelace verfasste bereits 1843 den ersten Algorithmus für eine Rechenmaschine.",
  },
  {
    id: "de_cafe_10",
    category: "☕ CAFÉ & KULTUR",
    text: "Aus welchem Land stammt die Kaffeepflanze ursprünglich?",
    options: { A: "Brasilien", B: "Äthiopien", C: "Kolumbien", D: "Jemen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Legende nach entdeckte ein Ziegenhirte namens Kaldi die Wirkung der Kaffeekirschen im äthiopischen Hochland.",
  },
  {
    id: "de_cafe_11",
    category: "☕ CAFÉ & KULTUR",
    text: "Was bedeutet 'Cappuccino' wörtlich übersetzt?",
    options: { A: "Kleine Kapuze", B: "Milchschaum", C: "Doppelter Kaffee", D: "Morgentrunk" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Der Name geht auf die Kapuzinermönche zurück – die Farbe ihrer Kutten erinnerte an den Kaffee mit Milch.",
  },
  {
    id: "de_cafe_12",
    category: "☕ CAFÉ & KULTUR",
    text: "Wie viele Espresso-Shots enthält ein klassischer Americano?",
    options: { A: "Keinen", B: "Einen oder zwei", C: "Genau vier", D: "Fünf" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Americano entstand, als US-Soldaten in Italien den Espresso mit heißem Wasser verdünnten.",
  },
  {
    id: "de_cafe_13",
    category: "☕ CAFÉ & KULTUR",
    text: "Welches Getränk besteht aus Espresso und einem Schuss Milchschaum?",
    options: { A: "Latte Macchiato", B: "Flat White", C: "Espresso Macchiato", D: "Mokka" },
    correctOption: "C",
    difficulty: 2,
    funFact: "'Macchiato' heißt 'gefleckt' – der Milchschaum hinterlässt einen Fleck auf dem Espresso.",
  },
  {
    id: "de_cafe_14",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche Teesorte wird am stärksten fermentiert?",
    options: { A: "Grüner Tee", B: "Weißer Tee", C: "Schwarzer Tee", D: "Kräutertee" },
    correctOption: "C",
    difficulty: 2,
    funFact: "In China heißt schwarzer Tee 'roter Tee' – nach der Farbe des Aufgusses, nicht der Blätter.",
  },
  {
    id: "de_cafe_15",
    category: "☕ CAFÉ & KULTUR",
    text: "Woraus wird Matcha hergestellt?",
    options: { A: "Gerösteten Reiskörnern", B: "Gemahlenen Grünteeblättern", C: "Getrockneten Minzblättern", D: "Fermentierten Kakaobohnen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Bei Matcha trinkt man das ganze Blatt mit – deshalb ist der Koffeingehalt höher als bei aufgegossenem Grüntee.",
  },
  {
    id: "de_cafe_16",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche Stadt ist für ihre traditionelle Kaffeehauskultur UNESCO-gelistet?",
    options: { A: "Paris", B: "Wien", C: "Lissabon", D: "Prag" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Wiener Kaffeehauskultur steht seit 2011 auf der UNESCO-Liste des immateriellen Kulturerbes.",
  },
  {
    id: "de_cafe_17",
    category: "☕ CAFÉ & KULTUR",
    text: "Was ist ein 'Flat White' im Vergleich zum Cappuccino?",
    options: { A: "Deutlich süßer", B: "Mit weniger, feinerem Milchschaum", C: "Ohne Espresso", D: "Immer kalt serviert" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Der Flat White kommt aus Australien und Neuseeland – beide Länder streiten bis heute über die Urheberschaft.",
  },
  {
    id: "de_cafe_18",
    category: "☕ CAFÉ & KULTUR",
    text: "Welches Gebäck wird traditionell zum Wiener Melange gereicht?",
    options: { A: "Croissant", B: "Bagel", C: "Kipferl", D: "Brezel" },
    correctOption: "C",
    difficulty: 3,
    funFact: "Das Kipferl gilt als Vorläufer des französischen Croissants.",
  },
  {
    id: "de_music_10",
    category: "🎵 MUSIK",
    text: "Welche Band veröffentlichte das Album 'The Dark Side of the Moon'?",
    options: { A: "Led Zeppelin", B: "Pink Floyd", C: "The Doors", D: "Queen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Das Album stand über 900 Wochen in den US-Charts – ein bis heute kaum gebrochener Rekord.",
  },
  {
    id: "de_music_11",
    category: "🎵 MUSIK",
    text: "Wie viele Saiten hat eine klassische Gitarre?",
    options: { A: "Vier", B: "Fünf", C: "Sechs", D: "Sieben" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Der Bass hat klassischerweise vier Saiten – deshalb verwechseln viele die beiden Instrumente beim Zählen.",
  },
  {
    id: "de_music_12",
    category: "🎵 MUSIK",
    text: "Aus welchem Land stammt der Musikstil Reggae?",
    options: { A: "Kuba", B: "Jamaika", C: "Brasilien", D: "Trinidad" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Bob Marleys 'Exodus' wurde vom Time Magazine zum Album des 20. Jahrhunderts gekürt.",
  },
  {
    id: "de_music_13",
    category: "🎵 MUSIK",
    text: "Welches Instrument spielte Miles Davis?",
    options: { A: "Saxofon", B: "Trompete", C: "Klavier", D: "Kontrabass" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Sein Album 'Kind of Blue' ist das meistverkaufte Jazzalbum aller Zeiten.",
  },
  {
    id: "de_music_14",
    category: "🎵 MUSIK",
    text: "Welche Stadt gilt als Geburtsort des Techno?",
    options: { A: "Berlin", B: "Detroit", C: "Manchester", D: "Chicago" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Berlin wurde später zur Techno-Hauptstadt Europas – erfunden wurde der Stil aber in Detroit.",
  },
  {
    id: "de_music_15",
    category: "🎵 MUSIK",
    text: "Wie viele Tasten hat ein Standard-Klavier?",
    options: { A: "76", B: "81", C: "88", D: "92" },
    correctOption: "C",
    difficulty: 2,
    funFact: "52 weiße und 36 schwarze Tasten ergeben zusammen genau 88.",
  },
  {
    id: "de_music_16",
    category: "🎵 MUSIK",
    text: "Welcher Komponist schrieb trotz zunehmender Taubheit weiter?",
    options: { A: "Mozart", B: "Beethoven", C: "Bach", D: "Chopin" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Seine 9. Sinfonie entstand, als er praktisch nichts mehr hören konnte.",
  },
  {
    id: "de_music_17",
    category: "🎵 MUSIK",
    text: "Was bezeichnet 'BPM' in der Musik?",
    options: { A: "Tonhöhe", B: "Lautstärke", C: "Schläge pro Minute", D: "Anzahl der Spuren" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Klassischer House liegt meist bei etwa 120–130 BPM.",
  },
  {
    id: "de_cinema_10",
    category: "🎬 KINO",
    text: "Welcher Film gewann als erster den Oscar für den besten Film?",
    options: { A: "Wings", B: "Metropolis", C: "Der Jazzsänger", D: "Nosferatu" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Wings' aus dem Jahr 1927 ist bis heute der einzige Stummfilm mit dieser Auszeichnung – neben 'The Artist' von 2011.",
  },
  {
    id: "de_cinema_11",
    category: "🎬 KINO",
    text: "Wer führte Regie bei 'Inception'?",
    options: { A: "Ridley Scott", B: "Christopher Nolan", C: "Denis Villeneuve", D: "David Fincher" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die berühmte sich drehende Flurszene wurde in einem real rotierenden Set gedreht, nicht am Computer.",
  },
  {
    id: "de_cinema_12",
    category: "🎬 KINO",
    text: "In welcher Stadt spielt der Film 'Lola rennt'?",
    options: { A: "Hamburg", B: "München", C: "Berlin", D: "Köln" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Der Film machte Franka Potente international bekannt und gilt als Meilenstein des deutschen Kinos der 90er.",
  },
  {
    id: "de_cinema_13",
    category: "🎬 KINO",
    text: "Welches Studio produzierte 'Der König der Löwen' von 1994?",
    options: { A: "Pixar", B: "Disney", C: "DreamWorks", D: "Warner Bros." },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Film war lange der erfolgreichste handgezeichnete Animationsfilm aller Zeiten.",
  },
  {
    id: "de_cinema_14",
    category: "🎬 KINO",
    text: "Welcher Schauspieler spielte in 'Das Leben der Anderen' den Stasi-Hauptmann?",
    options: { A: "Ulrich Mühe", B: "Bruno Ganz", C: "Moritz Bleibtreu", D: "Til Schweiger" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Der Film gewann 2007 den Oscar für den besten fremdsprachigen Film.",
  },
  {
    id: "de_cinema_15",
    category: "🎬 KINO",
    text: "Was ist ein 'Cameo' im Film?",
    options: { A: "Ein Drehbuchfehler", B: "Ein sehr kurzer Auftritt", C: "Eine Kamerafahrt", D: "Der Abspann" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Alfred Hitchcock hatte in fast allen seinen Filmen einen Cameo-Auftritt.",
  },
  {
    id: "de_brain_10",
    category: "🧠 DENKSPORT",
    text: "Ein Bauer hat 17 Schafe. Alle bis auf 9 laufen weg. Wie viele bleiben?",
    options: { A: "8", B: "9", C: "17", D: "0" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Alle bis auf 9' heißt: genau 9 bleiben übrig. Der Klassiker unter den Zahlenfallen.",
  },
  {
    id: "de_brain_11",
    category: "🧠 DENKSPORT",
    text: "Was wird nasser, je mehr es trocknet?",
    options: { A: "Die Sonne", B: "Ein Handtuch", C: "Ein Schwamm in der Sonne", D: "Papier" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ein Handtuch nimmt beim Trocknen anderer Dinge selbst Wasser auf.",
  },
  {
    id: "de_brain_12",
    category: "🧠 DENKSPORT",
    text: "Wie viele Monate haben 28 Tage?",
    options: { A: "Einer", B: "Zwei", C: "Alle zwölf", D: "Keiner" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Jeder Monat hat mindestens 28 Tage – gefragt war nicht 'genau 28'.",
  },
  {
    id: "de_brain_13",
    category: "🧠 DENKSPORT",
    text: "Ein Zug fährt nach Norden, der Wind weht nach Süden. Wohin zieht der Rauch?",
    options: { A: "Nach Norden", B: "Nach Süden", C: "Gar nicht, es ist ein E-Zug", D: "Nach Westen" },
    correctOption: "C",
    difficulty: 3,
    funFact: "Moderne Züge fahren elektrisch – kein Rauch, keine Richtung.",
  },
  {
    id: "de_brain_14",
    category: "🧠 DENKSPORT",
    text: "Was hat einen Hals, aber keinen Kopf?",
    options: { A: "Ein Schlüssel", B: "Eine Flasche", C: "Ein Schuh", D: "Ein Stuhl" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Auch Gitarren und Geigen haben einen Hals – aber ebenfalls keinen Kopf im Wortsinn.",
  },
  {
    id: "de_brain_15",
    category: "🧠 DENKSPORT",
    text: "Wenn drei Katzen in drei Minuten drei Mäuse fangen, wie lange brauchen 100 Katzen für 100 Mäuse?",
    options: { A: "Drei Minuten", B: "100 Minuten", C: "33 Minuten", D: "Eine Minute" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Jede Katze fängt eine Maus in drei Minuten – die Anzahl ändert daran nichts.",
  },
  {
    id: "de_brain_16",
    category: "🧠 DENKSPORT",
    text: "Was kann man fangen, aber nicht werfen?",
    options: { A: "Einen Ball", B: "Eine Erkältung", C: "Einen Stein", D: "Einen Blick" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Im Deutschen wie im Englischen 'fängt' man sich eine Erkältung ein.",
  },
  {
    id: "de_gen_10",
    category: "🌍 WISSEN",
    text: "Welches ist das größte Binnenmeer der Erde?",
    options: { A: "Schwarzes Meer", B: "Kaspisches Meer", C: "Ostsee", D: "Totes Meer" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Das Kaspische Meer ist so groß, dass bis heute gestritten wird, ob es ein See oder ein Meer ist.",
  },
  {
    id: "de_gen_11",
    category: "🌍 WISSEN",
    text: "Wie viele Bundesländer hat Deutschland?",
    options: { A: "14", B: "15", C: "16", D: "17" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Drei davon sind Stadtstaaten: Berlin, Hamburg und Bremen.",
  },
  {
    id: "de_gen_12",
    category: "🌍 WISSEN",
    text: "Welche Währung gilt in der Schweiz?",
    options: { A: "Euro", B: "Schweizer Franken", C: "Krone", D: "Schilling" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Schweiz ist von Euro-Ländern umgeben, hat den Euro aber nie eingeführt.",
  },
  {
    id: "de_gen_13",
    category: "🌍 WISSEN",
    text: "Welcher Fluss fließt durch Berlin?",
    options: { A: "Elbe", B: "Spree", C: "Oder", D: "Havel" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Spree mündet in Spandau in die Havel – beide fließen durch Berlin.",
  },
  {
    id: "de_gen_14",
    category: "🌍 WISSEN",
    text: "Welches Land hat die meisten Zeitzonen?",
    options: { A: "Russland", B: "USA", C: "China", D: "Frankreich" },
    correctOption: "D",
    difficulty: 3,
    funFact: "Durch seine Überseegebiete kommt Frankreich auf zwölf Zeitzonen – mehr als Russland.",
  },
  {
    id: "de_gen_15",
    category: "🌍 WISSEN",
    text: "Wie heißt die Hauptstadt von Australien?",
    options: { A: "Sydney", B: "Melbourne", C: "Canberra", D: "Brisbane" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Canberra wurde als Kompromiss gebaut, weil sich Sydney und Melbourne nicht einigen konnten.",
  },
  {
    id: "de_gen_16",
    category: "🌍 WISSEN",
    text: "Welches Tier ist das schnellste an Land?",
    options: { A: "Gepard", B: "Antilope", C: "Löwe", D: "Strauß" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Ein Gepard erreicht bis zu 110 km/h – hält das Tempo aber nur wenige Sekunden.",
  },
  {
    id: "de_gen_17",
    category: "🌍 WISSEN",
    text: "Wie viele Kontinente gibt es nach der gängigen deutschen Zählung?",
    options: { A: "Fünf", B: "Sechs", C: "Sieben", D: "Acht" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Je nach Land zählt man fünf, sechs oder sieben – eine reine Konventionsfrage.",
  },
  {
    id: "de_sci_10",
    category: "🚀 WISSENSCHAFT",
    text: "Welches Element hat das chemische Symbol 'Fe'?",
    options: { A: "Fluor", B: "Eisen", C: "Blei", D: "Silber" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Fe' kommt vom lateinischen 'ferrum'.",
  },
  {
    id: "de_sci_11",
    category: "🚀 WISSENSCHAFT",
    text: "Wie lange braucht das Licht von der Sonne zur Erde?",
    options: { A: "8 Sekunden", B: "8 Minuten", C: "8 Stunden", D: "8 Tage" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Wir sehen die Sonne immer so, wie sie vor gut acht Minuten aussah.",
  },
  {
    id: "de_sci_12",
    category: "🚀 WISSENSCHAFT",
    text: "Was misst ein Seismograf?",
    options: { A: "Luftdruck", B: "Erdbeben", C: "Luftfeuchtigkeit", D: "Schallpegel" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der erste bekannte Erdbebenmelder wurde im Jahr 132 in China gebaut.",
  },
  {
    id: "de_sci_13",
    category: "🚀 WISSENSCHAFT",
    text: "Welches Organ produziert Insulin?",
    options: { A: "Leber", B: "Niere", C: "Bauchspeicheldrüse", D: "Milz" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Insulin wurde 1921 entdeckt und veränderte die Behandlung von Diabetes grundlegend.",
  },
  {
    id: "de_sci_14",
    category: "🚀 WISSENSCHAFT",
    text: "Wofür steht 'KI' in der Technik?",
    options: { A: "Kinetische Induktion", B: "Künstliche Intelligenz", C: "Kritischer Index", D: "Kalte Ionisation" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der englische Begriff 'Artificial Intelligence' wurde 1956 auf einer Konferenz in Dartmouth geprägt.",
  },
  {
    id: "de_sci_15",
    category: "🚀 WISSENSCHAFT",
    text: "Welcher Planet ist der Sonne am nächsten?",
    options: { A: "Venus", B: "Merkur", C: "Mars", D: "Erde" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Trotz der Nähe zur Sonne ist die Venus der heißeste Planet – wegen ihrer dichten Atmosphäre.",
  },
  {
    id: "de_sci_16",
    category: "🚀 WISSENSCHAFT",
    text: "Was bezeichnet der Begriff 'Byte'?",
    options: { A: "Acht Bit", B: "Zehn Bit", C: "Ein Bit", D: "Tausend Bit" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Ein Kilobyte sind technisch 1024 Byte, nicht 1000 – daher stimmen Festplattenangaben oft nicht mit der Anzeige überein.",
  },
  {
    id: "de_night_10",
    category: "🍸 NACHTLEBEN",
    text: "Was ist ein 'Mocktail'?",
    options: { A: "Ein Cocktail ohne Alkohol", B: "Ein doppelter Cocktail", C: "Ein warmer Cocktail", D: "Ein Cocktail mit Kaffee" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Der Name ist ein Wortspiel aus 'mock' (nachgemacht) und 'Cocktail'.",
  },
  {
    id: "de_night_11",
    category: "🍸 NACHTLEBEN",
    text: "Welche Frucht gehört klassisch in eine Limonade?",
    options: { A: "Zitrone", B: "Ananas", C: "Banane", D: "Kirsche" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Das Wort 'Limonade' geht auf das persische 'limun' für Zitrone zurück.",
  },
  {
    id: "de_night_12",
    category: "🍸 NACHTLEBEN",
    text: "Was ist Ayran?",
    options: { A: "Ein Joghurtgetränk", B: "Ein Fruchtsaft", C: "Ein Kräutertee", D: "Ein Gebäck" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Ayran wird aus Joghurt, Wasser und Salz gemixt und ist in der Türkei das Standardgetränk zum Essen.",
  },
  {
    id: "de_cafe_20",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche Milch schäumt wegen ihres Proteingehalts am besten?",
    options: { A: "Vollmilch", B: "Reismilch", C: "Kokosmilch", D: "Mandelmilch" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Beim Aufschäumen stabilisieren Milchproteine die Luftbläschen – Pflanzendrinks brauchen dafür oft Zusätze.",
  },
  {
    id: "de_cafe_21",
    category: "☕ CAFÉ & KULTUR",
    text: "Was ist 'Cold Brew'?",
    options: { A: "Heiß gebrühter, dann gekühlter Kaffee", B: "Kalt extrahierter Kaffee", C: "Kaffee mit Eiscreme", D: "Gefrorener Espresso" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Die Extraktion dauert 12 bis 24 Stunden – das Ergebnis schmeckt milder und weniger sauer.",
  },
  {
    id: "de_cafe_22",
    category: "☕ CAFÉ & KULTUR",
    text: "Welche zwei Kaffeearten dominieren den Weltmarkt?",
    options: { A: "Arabica und Robusta", B: "Mokka und Latte", C: "Java und Sumatra", D: "Bourbon und Typica" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Robusta enthält etwa doppelt so viel Koffein wie Arabica.",
  },
  {
    id: "de_cafe_23",
    category: "☕ CAFÉ & KULTUR",
    text: "Welches Land trinkt pro Kopf am meisten Kaffee?",
    options: { A: "Italien", B: "Finnland", C: "Brasilien", D: "Türkei" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Finnland liegt seit Jahren an der Spitze – mit deutlich über acht Kilogramm pro Kopf und Jahr.",
  },
  {
    id: "de_cafe_24",
    category: "☕ CAFÉ & KULTUR",
    text: "Wie wird türkischer Kaffee traditionell zubereitet?",
    options: { A: "Mit einer Filtermaschine", B: "In einem Kupferkännchen", C: "Mit einer Presse", D: "Im Wasserkocher" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Das Kännchen heißt Cezve; der Kaffeesatz bleibt in der Tasse und wird traditionell gedeutet.",
  },
  {
    id: "de_cafe_25",
    category: "☕ CAFÉ & KULTUR",
    text: "Was ist Latte Art?",
    options: { A: "Ein Kaffeebohnen-Muster", B: "Muster im Milchschaum", C: "Bemalte Tassen", D: "Eine Röstmethode" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Herz und Rosetta gelten als die beiden Grundfiguren jeder Latte Art.",
  },
  {
    id: "de_music_20",
    category: "🎵 MUSIK",
    text: "Welcher Künstler veröffentlichte das Album '25'?",
    options: { A: "Adele", B: "Beyoncé", C: "Rihanna", D: "Taylor Swift" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Adele benennt ihre Alben nach ihrem Alter während des Entstehungsprozesses.",
  },
  {
    id: "de_music_21",
    category: "🎵 MUSIK",
    text: "Welches Genre entstand in den 1970ern in der Bronx?",
    options: { A: "Hip-Hop", B: "Punk", C: "Disco", D: "Soul" },
    correctOption: "A",
    difficulty: 2,
    funFact: "DJ Kool Hercs Blockpartys gelten als Geburtsstunde des Hip-Hop.",
  },
  {
    id: "de_music_22",
    category: "🎵 MUSIK",
    text: "Wie viele Musiker hatten die Beatles in ihrer bekanntesten Besetzung?",
    options: { A: "Drei", B: "Vier", C: "Fünf", D: "Sechs" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Vor Ringo Starr saß Pete Best am Schlagzeug – er verließ die Band kurz vor dem Durchbruch.",
  },
  {
    id: "de_music_23",
    category: "🎵 MUSIK",
    text: "Was ist ein 'A cappella'-Stück?",
    options: { A: "Nur mit Klavier", B: "Ohne Instrumente", C: "Nur instrumental", D: "Mit Orchester" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Der Begriff kommt aus dem Italienischen und bedeutet 'nach Art der Kapelle'.",
  },
  {
    id: "de_cinema_20",
    category: "🎬 KINO",
    text: "Welcher Film spielte als erster weltweit über zwei Milliarden Dollar ein?",
    options: { A: "Titanic", B: "Avatar", C: "Avengers: Endgame", D: "Star Wars" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Titanic' knackte die Marke 1998 – erst 'Avatar' übertraf den Rekord elf Jahre später.",
  },
  {
    id: "de_cinema_21",
    category: "🎬 KINO",
    text: "Welche Serie spielt im fiktiven Königreich Westeros?",
    options: { A: "The Witcher", B: "Game of Thrones", C: "Vikings", D: "The Crown" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Die Serie wurde unter anderem in Nordirland, Kroatien und Island gedreht.",
  },
  {
    id: "de_cinema_22",
    category: "🎬 KINO",
    text: "Wer spielte die Hauptrolle in 'Forrest Gump'?",
    options: { A: "Tom Hanks", B: "Tom Cruise", C: "Kevin Costner", D: "Robin Williams" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Tom Hanks gewann in zwei aufeinanderfolgenden Jahren den Oscar als bester Hauptdarsteller.",
  },
  {
    id: "de_cinema_23",
    category: "🎬 KINO",
    text: "Was bedeutet die Abkürzung 'CGI'?",
    options: { A: "Computergenerierte Bilder", B: "Klassische Filmtechnik", C: "Kameraführung", D: "Farbkorrektur" },
    correctOption: "A",
    difficulty: 2,
    funFact: "'Tron' von 1982 gilt als einer der ersten Filme mit umfangreichem CGI-Einsatz.",
  },
  {
    id: "de_brain_20",
    category: "🧠 DENKSPORT",
    text: "Wie oft kann man 10 von 100 abziehen?",
    options: { A: "Zehnmal", B: "Einmal", C: "Neunmal", D: "Unendlich oft" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Nach dem ersten Abziehen ist es nicht mehr 100, sondern 90.",
  },
  {
    id: "de_brain_21",
    category: "🧠 DENKSPORT",
    text: "Zwei Väter und zwei Söhne gehen angeln, jeder fängt einen Fisch. Es sind nur drei Fische. Wie geht das?",
    options: { A: "Einer schummelt", B: "Großvater, Vater, Sohn", C: "Ein Fisch entkam", D: "Sie teilen sich einen" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Der mittlere ist gleichzeitig Vater und Sohn – drei Personen, vier Rollen.",
  },
  {
    id: "de_brain_22",
    category: "🧠 DENKSPORT",
    text: "Was geht hoch und kommt nie wieder herunter?",
    options: { A: "Ein Ballon", B: "Das Alter", C: "Der Rauch", D: "Ein Pfeil" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ein Rätsel, das in fast jeder Sprache existiert.",
  },
  {
    id: "de_gen_20",
    category: "🌍 WISSEN",
    text: "Welches Land hat die längste Küstenlinie der Welt?",
    options: { A: "Russland", B: "Kanada", C: "Australien", D: "Indonesien" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Kanadas Küstenlinie ist über 200.000 Kilometer lang – wegen der unzähligen arktischen Inseln.",
  },
  {
    id: "de_gen_21",
    category: "🌍 WISSEN",
    text: "Wie viele Spieler stehen bei einem Fußballspiel pro Mannschaft auf dem Feld?",
    options: { A: "Neun", B: "Zehn", C: "Elf", D: "Zwölf" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Der Torwart ist der einzige Feldspieler, der den Ball im eigenen Strafraum mit der Hand berühren darf.",
  },
  {
    id: "de_gen_22",
    category: "🌍 WISSEN",
    text: "Welche Sprache hat weltweit die meisten Muttersprachler?",
    options: { A: "Englisch", B: "Spanisch", C: "Mandarin", D: "Hindi" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Englisch führt erst, wenn man Zweitsprachler mitzählt.",
  },
  {
    id: "de_sci_20",
    category: "🚀 WISSENSCHAFT",
    text: "Was ist die häufigste Substanz im menschlichen Körper?",
    options: { A: "Eiweiß", B: "Wasser", C: "Fett", D: "Kalzium" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Etwa 60 Prozent des Körpergewichts eines Erwachsenen bestehen aus Wasser.",
  },
  {
    id: "de_sci_21",
    category: "🚀 WISSENSCHAFT",
    text: "Welches Gas atmen Pflanzen bei der Fotosynthese auf?",
    options: { A: "Sauerstoff", B: "Stickstoff", C: "Kohlendioxid", D: "Wasserstoff" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Sie geben dabei Sauerstoff ab – genau umgekehrt zu unserer Atmung.",
  },
  {
    id: "de_sci_22",
    category: "🚀 WISSENSCHAFT",
    text: "Wie viele Knochen hat ein erwachsener Mensch etwa?",
    options: { A: "106", B: "206", C: "306", D: "406" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Babys kommen mit rund 300 Knochen zur Welt – viele verwachsen im Laufe des Wachstums.",
  },
  {
    id: "de_sci_23",
    category: "🚀 WISSENSCHAFT",
    text: "Was bedeutet 'Open Source' bei Software?",
    options: { A: "Kostenlos, aber geheim", B: "Quellcode ist öffentlich einsehbar", C: "Nur im Browser nutzbar", D: "Ohne Internet nutzbar" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Linux ist das bekannteste Open-Source-Projekt und läuft auf den meisten Servern weltweit.",
  },
  {
    id: "de_gen_24",
    category: "🌍 WISSEN",
    text: "Welches Meer grenzt im Norden an Deutschland?",
    options: { A: "Nur die Nordsee", B: "Nordsee und Ostsee", C: "Nur die Ostsee", D: "Das Mittelmeer" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Schleswig-Holstein ist das einzige Bundesland mit Küste an beiden Meeren.",
  },
];
