import type { QuizQuestion } from "../../types/database";

// HENGAME quiz havuzu — EN. Secim ve filtreleme mantigi
// src/lib/quizQuestions.ts icinde; burasi sadece veri.

export const enQuestions: QuizQuestion[] = [
  // ─── NIGHTLIFE & CAFE ───
  {
    id: "en_night_1",
    category: "🍸 NIGHTLIFE",
    text: "Which herb gives a virgin mojito its character?",
    options: { A: "Basil", B: "Mint", C: "Thyme", D: "Rosemary" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Mint leaves should be pressed gently, not crushed — crushing turns them bitter.",
  },
  {
    id: "en_night_2",
    category: "🍸 NIGHTLIFE",
    text: "What is the golden foam layer on top of an espresso called?",
    options: { A: "Cream", B: "Crema", C: "Head", D: "Froth" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Crema forms when carbon dioxide from fresh beans emulsifies with the coffee oils under pressure; stale beans produce almost none.",
  },

  // ─── MUSIC & POP CULTURE ───
  {
    id: "en_music_1",
    category: "🎵 MUSIC",
    text: "Which song was the first in Spotify history to surpass 3 billion streams?",
    options: { A: "Blinding Lights", B: "Shape of You", C: "Despacito", D: "Starboy" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Ed Sheeran's 'Shape of You' crossed 3 billion streams in December 2021.",
  },
  {
    id: "en_music_2",
    category: "🎵 MUSIC",
    text: "What year was Queen's iconic 'Bohemian Rhapsody' released?",
    options: { A: "1969", B: "1975", C: "1982", D: "1989" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Record executives initially thought the 6-minute operatic track would never work on radio!",
  },

  // ─── CINEMA & TV ───
  {
    id: "en_cinema_1",
    category: "🎬 MOVIES",
    text: "In 'The Matrix', which pill does Neo take to see the real world?",
    options: { A: "Blue Pill", B: "Red Pill", C: "Green Pill", D: "Yellow Pill" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The red pill represents truth and reality, while the blue pill maintains the illusion.",
  },
  {
    id: "en_cinema_2",
    category: "🎬 MOVIES",
    text: "Where was the One Ring forged in 'The Lord of the Rings'?",
    options: { A: "Mount Doom", B: "The Lonely Mountain", C: "Misty Mountains", D: "Isengard" },
    correctOption: "A",
    difficulty: 1,
    funFact: "The One Ring could only be unmade in the fires of Mount Doom where it was forged.",
  },

  // ─── BRAIN TEASERS ───
  {
    id: "en_brain_1",
    category: "🧠 BRAIN TEASER",
    text: "If you overtake the second person in a race, what position are you in?",
    options: { A: "1st", B: "2nd", C: "3rd", D: "Winner" },
    correctOption: "B",
    difficulty: 1,
    funFact: "You take the place of the person in 2nd; the person in 1st is still ahead of you!",
  },
  {
    id: "en_brain_2",
    category: "🧠 BRAIN TEASER",
    text: "Some months have 30 days, some have 31. How many months have 28 days?",
    options: { A: "1 (February)", B: "6", C: "All 12", D: "None" },
    correctOption: "C",
    difficulty: 2,
    funFact: "All 12 months have at least 28 days!",
  },

  // ─── GENERAL KNOWLEDGE ───
  {
    id: "en_gen_1",
    category: "🌍 TRIVIA",
    text: "Which chemical element is represented by the symbol 'Au'?",
    options: { A: "Silver", B: "Gold", C: "Aluminum", D: "Copper" },
    correctOption: "B",
    difficulty: 1,
    funFact: "'Au' comes from the Latin word 'Aurum', meaning 'shining dawn'.",
  },
  {
    id: "en_gen_2",
    category: "🌍 TRIVIA",
    text: "In which museum is the Mona Lisa currently displayed?",
    options: { A: "The British Museum", B: "The Prado", C: "The Louvre", D: "The Met" },
    correctOption: "C",
    difficulty: 1,
    funFact: "The Mona Lisa has her own mailbox at the Louvre and receives love letters every year!",
  },

  // ─── SCIENCE & TECH ───
  {
    id: "en_sci_1",
    category: "🚀 SCIENCE",
    text: "Which planet is the hottest in our solar system?",
    options: { A: "Mercury", B: "Venus", C: "Mars", D: "Jupiter" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Due to its thick carbon dioxide atmosphere and runaway greenhouse effect, Venus reaches 465°C!",
  },
  {
    id: "en_sci_2",
    category: "🚀 SCIENCE",
    text: "How many hearts does an octopus have?",
    options: { A: "1", B: "2", C: "3", D: "4" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Octopuses have 3 hearts and blue copper-based blood!",
  },
  {
    id: "en_sci_3",
    category: "🚀 SCIENCE",
    text: "Who is widely considered the world's first computer programmer?",
    options: { A: "Alan Turing", B: "Ada Lovelace", C: "Charles Babbage", D: "Grace Hopper" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Ada Lovelace wrote the very first algorithm intended for Babbage's Analytical Engine in 1843.",
  },
  {
    id: "en_cafe_10",
    category: "☕ CAFÉ & CULTURE",
    text: "Which country is the original home of the coffee plant?",
    options: { A: "Brazil", B: "Ethiopia", C: "Colombia", D: "Yemen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Legend credits a goat herder named Kaldi with noticing how the coffee cherries energised his goats.",
  },
  {
    id: "en_cafe_11",
    category: "☕ CAFÉ & CULTURE",
    text: "What does 'macchiato' mean in Italian?",
    options: { A: "Stained", B: "Strong", C: "Sweet", D: "Layered" },
    correctOption: "A",
    difficulty: 2,
    funFact: "The foam leaves a 'stain' on the espresso — hence the name.",
  },
  {
    id: "en_cafe_12",
    category: "☕ CAFÉ & CULTURE",
    text: "What is cold brew coffee?",
    options: { A: "Hot coffee poured over ice", B: "Coffee extracted with cold water over many hours", C: "Frozen espresso", D: "Coffee with ice cream" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Steeping for 12 to 24 hours produces a smoother, less acidic cup.",
  },
  {
    id: "en_cafe_13",
    category: "☕ CAFÉ & CULTURE",
    text: "Which two coffee species dominate world production?",
    options: { A: "Arabica and Robusta", B: "Mocha and Latte", C: "Java and Sumatra", D: "Bourbon and Typica" },
    correctOption: "A",
    difficulty: 2,
    funFact: "Robusta carries roughly twice the caffeine of Arabica.",
  },
  {
    id: "en_cafe_14",
    category: "☕ CAFÉ & CULTURE",
    text: "What is matcha made from?",
    options: { A: "Roasted rice", B: "Ground green tea leaves", C: "Dried mint", D: "Fermented cocoa" },
    correctOption: "B",
    difficulty: 1,
    funFact: "You drink the whole leaf, which is why matcha has more caffeine than steeped green tea.",
  },
  {
    id: "en_cafe_15",
    category: "☕ CAFÉ & CULTURE",
    text: "Which city's coffee house culture is on the UNESCO heritage list?",
    options: { A: "Paris", B: "Vienna", C: "Lisbon", D: "Istanbul" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Viennese coffee house culture was inscribed in 2011 as intangible cultural heritage.",
  },
  {
    id: "en_cafe_16",
    category: "☕ CAFÉ & CULTURE",
    text: "How does a flat white differ from a cappuccino?",
    options: { A: "It is sweeter", B: "It has less, finer foam", C: "It has no espresso", D: "It is always iced" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Australia and New Zealand still argue over which country invented it.",
  },
  {
    id: "en_cafe_17",
    category: "☕ CAFÉ & CULTURE",
    text: "Which tea is the most heavily oxidised?",
    options: { A: "Green tea", B: "White tea", C: "Black tea", D: "Herbal tea" },
    correctOption: "C",
    difficulty: 2,
    funFact: "In China it is called 'red tea', after the colour of the liquid rather than the leaf.",
  },
  {
    id: "en_cafe_18",
    category: "☕ CAFÉ & CULTURE",
    text: "What is a mocktail?",
    options: { A: "A cocktail without alcohol", B: "A double cocktail", C: "A hot cocktail", D: "A coffee cocktail" },
    correctOption: "A",
    difficulty: 1,
    funFact: "The name is a play on 'mock' and 'cocktail'.",
  },
  {
    id: "en_music_10",
    category: "🎵 MUSIC",
    text: "Which band released 'The Dark Side of the Moon'?",
    options: { A: "Led Zeppelin", B: "Pink Floyd", C: "The Doors", D: "Queen" },
    correctOption: "B",
    difficulty: 1,
    funFact: "It spent more than 900 weeks on the US charts.",
  },
  {
    id: "en_music_11",
    category: "🎵 MUSIC",
    text: "Which city is considered the birthplace of techno?",
    options: { A: "Berlin", B: "Detroit", C: "Manchester", D: "Chicago" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Berlin later became Europe's techno capital, but the sound started in Detroit.",
  },
  {
    id: "en_music_12",
    category: "🎵 MUSIC",
    text: "How many keys does a standard piano have?",
    options: { A: "76", B: "81", C: "88", D: "92" },
    correctOption: "C",
    difficulty: 2,
    funFact: "52 white keys plus 36 black ones make exactly 88.",
  },
  {
    id: "en_music_13",
    category: "🎵 MUSIC",
    text: "Which instrument did Miles Davis play?",
    options: { A: "Saxophone", B: "Trumpet", C: "Piano", D: "Double bass" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Kind of Blue' is the best-selling jazz album of all time.",
  },
  {
    id: "en_music_14",
    category: "🎵 MUSIC",
    text: "What does BPM measure in music?",
    options: { A: "Pitch", B: "Volume", C: "Beats per minute", D: "Track count" },
    correctOption: "C",
    difficulty: 1,
    funFact: "Classic house usually sits around 120 to 130 BPM.",
  },
  {
    id: "en_music_15",
    category: "🎵 MUSIC",
    text: "Which genre emerged in the Bronx in the 1970s?",
    options: { A: "Hip-hop", B: "Punk", C: "Disco", D: "Soul" },
    correctOption: "A",
    difficulty: 2,
    funFact: "DJ Kool Herc's block parties are widely seen as the starting point.",
  },
  {
    id: "en_music_16",
    category: "🎵 MUSIC",
    text: "What does 'a cappella' mean?",
    options: { A: "With piano only", B: "Without instruments", C: "Instrumental only", D: "With an orchestra" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The Italian phrase means 'in the manner of the chapel'.",
  },
  {
    id: "en_cinema_10",
    category: "🎬 MOVIES",
    text: "Who directed 'Inception'?",
    options: { A: "Ridley Scott", B: "Christopher Nolan", C: "Denis Villeneuve", D: "David Fincher" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The rotating corridor fight was filmed on a real spinning set, not with CGI.",
  },
  {
    id: "en_cinema_11",
    category: "🎬 MOVIES",
    text: "Which fictional kingdom is the setting of 'Game of Thrones'?",
    options: { A: "Narnia", B: "Westeros", C: "Middle-earth", D: "Panem" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Filming took place in Northern Ireland, Croatia and Iceland among others.",
  },
  {
    id: "en_cinema_12",
    category: "🎬 MOVIES",
    text: "Who starred as the title character in 'Forrest Gump'?",
    options: { A: "Tom Hanks", B: "Tom Cruise", C: "Kevin Costner", D: "Robin Williams" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Hanks won the Best Actor Oscar two years running.",
  },
  {
    id: "en_cinema_13",
    category: "🎬 MOVIES",
    text: "What is a cameo in film?",
    options: { A: "A scripting error", B: "A very brief appearance", C: "A camera move", D: "The closing credits" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Alfred Hitchcock appeared in almost all of his own films.",
  },
  {
    id: "en_cinema_14",
    category: "🎬 MOVIES",
    text: "Which film was the first to gross over two billion dollars worldwide?",
    options: { A: "Titanic", B: "Avatar", C: "Avengers: Endgame", D: "Star Wars" },
    correctOption: "A",
    difficulty: 3,
    funFact: "'Titanic' passed the mark in 1998; 'Avatar' beat the record eleven years later.",
  },
  {
    id: "en_cinema_15",
    category: "🎬 MOVIES",
    text: "What does CGI stand for?",
    options: { A: "Computer-generated imagery", B: "Classic guided input", C: "Central grading interface", D: "Colour grading index" },
    correctOption: "A",
    difficulty: 2,
    funFact: "'Tron' from 1982 is often cited as one of the first films with extensive CGI.",
  },
  {
    id: "en_brain_10",
    category: "🧠 BRAIN TEASER",
    text: "A farmer has 17 sheep. All but 9 run away. How many are left?",
    options: { A: "8", B: "9", C: "17", D: "0" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'All but 9' means exactly 9 stay. A classic number trap.",
  },
  {
    id: "en_brain_11",
    category: "🧠 BRAIN TEASER",
    text: "How many months have 28 days?",
    options: { A: "One", B: "Two", C: "All twelve", D: "None" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Every month has at least 28 days — the question never said 'exactly'.",
  },
  {
    id: "en_brain_12",
    category: "🧠 BRAIN TEASER",
    text: "What gets wetter the more it dries?",
    options: { A: "The sun", B: "A towel", C: "Paper", D: "A sponge" },
    correctOption: "B",
    difficulty: 2,
    funFact: "A towel soaks up water as it dries everything else.",
  },
  {
    id: "en_brain_13",
    category: "🧠 BRAIN TEASER",
    text: "If three cats catch three mice in three minutes, how long do 100 cats need for 100 mice?",
    options: { A: "Three minutes", B: "100 minutes", C: "33 minutes", D: "One minute" },
    correctOption: "A",
    difficulty: 3,
    funFact: "Each cat takes three minutes per mouse; scaling up changes nothing.",
  },
  {
    id: "en_brain_14",
    category: "🧠 BRAIN TEASER",
    text: "What has a neck but no head?",
    options: { A: "A key", B: "A bottle", C: "A shoe", D: "A chair" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Guitars and violins have necks too — and also no heads.",
  },
  {
    id: "en_brain_15",
    category: "🧠 BRAIN TEASER",
    text: "How many times can you subtract 10 from 100?",
    options: { A: "Ten times", B: "Once", C: "Nine times", D: "Infinitely" },
    correctOption: "B",
    difficulty: 2,
    funFact: "After the first subtraction it is no longer 100, it is 90.",
  },
  {
    id: "en_brain_16",
    category: "🧠 BRAIN TEASER",
    text: "What goes up and never comes back down?",
    options: { A: "A balloon", B: "Your age", C: "Smoke", D: "An arrow" },
    correctOption: "B",
    difficulty: 2,
    funFact: "A riddle that exists in almost every language.",
  },
  {
    id: "en_gen_10",
    category: "🌍 TRIVIA",
    text: "Which country has the longest coastline in the world?",
    options: { A: "Russia", B: "Canada", C: "Australia", D: "Indonesia" },
    correctOption: "B",
    difficulty: 3,
    funFact: "Canada's coastline runs over 200,000 kilometres thanks to its Arctic islands.",
  },
  {
    id: "en_gen_11",
    category: "🌍 TRIVIA",
    text: "What is the capital of Australia?",
    options: { A: "Sydney", B: "Melbourne", C: "Canberra", D: "Brisbane" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Canberra was purpose-built as a compromise between Sydney and Melbourne.",
  },
  {
    id: "en_gen_12",
    category: "🌍 TRIVIA",
    text: "Which language has the most native speakers?",
    options: { A: "English", B: "Spanish", C: "Mandarin", D: "Hindi" },
    correctOption: "C",
    difficulty: 2,
    funFact: "English only takes the lead once second-language speakers are counted.",
  },
  {
    id: "en_gen_13",
    category: "🌍 TRIVIA",
    text: "In which year did the Berlin Wall fall?",
    options: { A: "1987", B: "1989", C: "1990", D: "1991" },
    correctOption: "B",
    difficulty: 1,
    funFact: "The border opened on 9 November 1989 after a garbled press conference.",
  },
  {
    id: "en_gen_14",
    category: "🌍 TRIVIA",
    text: "Which country has the most time zones?",
    options: { A: "Russia", B: "USA", C: "China", D: "France" },
    correctOption: "D",
    difficulty: 3,
    funFact: "Counting its overseas territories, France spans twelve time zones.",
  },
  {
    id: "en_gen_15",
    category: "🌍 TRIVIA",
    text: "What is the largest inland body of water on Earth?",
    options: { A: "Black Sea", B: "Caspian Sea", C: "Lake Superior", D: "Dead Sea" },
    correctOption: "B",
    difficulty: 2,
    funFact: "It is so large that people still argue whether it is a lake or a sea.",
  },
  {
    id: "en_gen_16",
    category: "🌍 TRIVIA",
    text: "Which animal is the fastest on land?",
    options: { A: "Cheetah", B: "Antelope", C: "Lion", D: "Ostrich" },
    correctOption: "A",
    difficulty: 1,
    funFact: "A cheetah hits about 110 km/h but can only hold it for a few seconds.",
  },
  {
    id: "en_gen_17",
    category: "🌍 TRIVIA",
    text: "How many players per team are on the pitch in football?",
    options: { A: "Nine", B: "Ten", C: "Eleven", D: "Twelve" },
    correctOption: "C",
    difficulty: 1,
    funFact: "The goalkeeper is the only one allowed to handle the ball inside their own penalty area.",
  },
  {
    id: "en_sci_10",
    category: "🚀 SCIENCE",
    text: "Which element has the symbol 'Fe'?",
    options: { A: "Fluorine", B: "Iron", C: "Lead", D: "Silver" },
    correctOption: "B",
    difficulty: 2,
    funFact: "'Fe' comes from the Latin 'ferrum'.",
  },
  {
    id: "en_sci_11",
    category: "🚀 SCIENCE",
    text: "How long does sunlight take to reach Earth?",
    options: { A: "8 seconds", B: "8 minutes", C: "8 hours", D: "8 days" },
    correctOption: "B",
    difficulty: 2,
    funFact: "We always see the sun as it looked about eight minutes ago.",
  },
  {
    id: "en_sci_12",
    category: "🚀 SCIENCE",
    text: "Which organ produces insulin?",
    options: { A: "Liver", B: "Kidney", C: "Pancreas", D: "Spleen" },
    correctOption: "C",
    difficulty: 2,
    funFact: "Insulin was isolated in 1921 and transformed diabetes treatment.",
  },
  {
    id: "en_sci_13",
    category: "🚀 SCIENCE",
    text: "Which planet is closest to the sun?",
    options: { A: "Venus", B: "Mercury", C: "Mars", D: "Earth" },
    correctOption: "B",
    difficulty: 1,
    funFact: "Venus is still the hottest planet, thanks to its thick atmosphere.",
  },
  {
    id: "en_sci_14",
    category: "🚀 SCIENCE",
    text: "How many bits are in a byte?",
    options: { A: "Eight", B: "Ten", C: "One", D: "A thousand" },
    correctOption: "A",
    difficulty: 2,
    funFact: "A kilobyte is technically 1024 bytes, which is why drive sizes never quite match the label.",
  },
  {
    id: "en_sci_15",
    category: "🚀 SCIENCE",
    text: "Roughly how many bones does an adult human have?",
    options: { A: "106", B: "206", C: "306", D: "406" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Babies are born with around 300; many fuse together as they grow.",
  },
  {
    id: "en_sci_16",
    category: "🚀 SCIENCE",
    text: "Which gas do plants take in during photosynthesis?",
    options: { A: "Oxygen", B: "Nitrogen", C: "Carbon dioxide", D: "Hydrogen" },
    correctOption: "C",
    difficulty: 1,
    funFact: "They release oxygen in return — the reverse of our breathing.",
  },
  {
    id: "en_sci_17",
    category: "🚀 SCIENCE",
    text: "What does 'open source' mean for software?",
    options: { A: "Free but secret", B: "The source code is publicly viewable", C: "Browser-only", D: "Works offline" },
    correctOption: "B",
    difficulty: 2,
    funFact: "Linux is the best-known open-source project and runs most of the world's servers.",
  },
  {
    id: "en_night_10",
    category: "🍸 NIGHTLIFE",
    text: "What is ayran?",
    options: { A: "A yoghurt drink", B: "A fruit juice", C: "A herbal tea", D: "A pastry" },
    correctOption: "A",
    difficulty: 1,
    funFact: "Yoghurt, water and salt — the default drink with a meal in Turkey.",
  },
  {
    id: "en_night_11",
    category: "🍸 NIGHTLIFE",
    text: "Which fruit gives classic lemonade its name?",
    options: { A: "Lemon", B: "Pineapple", C: "Banana", D: "Cherry" },
    correctOption: "A",
    difficulty: 1,
    funFact: "The word traces back to the Persian 'limun'.",
  },
];
